#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMET.Server.Domain
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GAM_Complex_Op")]
	public partial class BoundaryDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BoundaryDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BoundaryDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BoundaryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BoundaryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SWC_LKP> SWC_LKPs
		{
			get
			{
				return this.GetTable<SWC_LKP>();
			}
		}
		
		public System.Data.Linq.Table<LATA_CENTROID> LATA_CENTROIDs
		{
			get
			{
				return this.GetTable<LATA_CENTROID>();
			}
		}
		
		public System.Data.Linq.Table<LATA_BOUNDARY_LKP> LATA_BOUNDARY_LKPs
		{
			get
			{
				return this.GetTable<LATA_BOUNDARY_LKP>();
			}
		}
		
		public System.Data.Linq.Table<Level3_RouteMap> Level3_RouteMaps
		{
			get
			{
				return this.GetTable<Level3_RouteMap>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="COMET.SWC_IN_BOUNDARY", IsComposable=true)]
		public IQueryable<SWC_IN_BOUNDARYResult> SWC_IN_BOUNDARY([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BottomLeftLat", DbType="VarChar(25)")] string bottomLeftLat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BottomLeftLng", DbType="VarChar(25)")] string bottomLeftLng, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TopRightLat", DbType="VarChar(25)")] string topRightLat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TopRightLng", DbType="VarChar(25)")] string topRightLng)
		{
			return this.CreateMethodCallQuery<SWC_IN_BOUNDARYResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bottomLeftLat, bottomLeftLng, topRightLat, topRightLng);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="COMET.LATA_IN_BOUNDARY", IsComposable=true)]
		public IQueryable<LATA_IN_BOUNDARYResult> LATA_IN_BOUNDARY([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BottomLeftLat", DbType="VarChar(25)")] string bottomLeftLat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BottomLeftLng", DbType="VarChar(25)")] string bottomLeftLng, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TopRightLat", DbType="VarChar(25)")] string topRightLat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TopRightLng", DbType="VarChar(25)")] string topRightLng)
		{
			return this.CreateMethodCallQuery<LATA_IN_BOUNDARYResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bottomLeftLat, bottomLeftLng, topRightLat, topRightLng);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="COMET.L3FIBER_INBOUNDARY_REDUCE", IsComposable=true)]
		public IQueryable<L3FIBER_INBOUNDARY_REDUCEResult> L3FIBER_INBOUNDARY_REDUCE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BottomLeftLat", DbType="VarChar(25)")] string bottomLeftLat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BottomLeftLng", DbType="VarChar(25)")] string bottomLeftLng, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TopRightLat", DbType="VarChar(25)")] string topRightLat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TopRightLng", DbType="VarChar(25)")] string topRightLng)
		{
			return this.CreateMethodCallQuery<L3FIBER_INBOUNDARY_REDUCEResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bottomLeftLat, bottomLeftLng, topRightLat, topRightLng);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="COMET.MSO_IN_BOUNDARY", IsComposable=true)]
		public IQueryable<MSO_IN_BOUNDARYResult> MSO_IN_BOUNDARY([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BottomLeftLat", DbType="VarChar(25)")] string bottomLeftLat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BottomLeftLng", DbType="VarChar(25)")] string bottomLeftLng, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TopRightLat", DbType="VarChar(25)")] string topRightLat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TopRightLng", DbType="VarChar(25)")] string topRightLng)
		{
			return this.CreateMethodCallQuery<MSO_IN_BOUNDARYResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bottomLeftLat, bottomLeftLng, topRightLat, topRightLng);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="COMET.SWC_LKP")]
	public partial class SWC_LKP
	{
		
		private string _SWC_CLLI;
		
		private string _DOM_SWITCH;
		
		private string _COORDINATES;
		
		private System.Nullable<decimal> _CentroidLat;
		
		private System.Nullable<decimal> _CentroidLng;
		
		public SWC_LKP()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SWC_CLLI", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string SWC_CLLI
		{
			get
			{
				return this._SWC_CLLI;
			}
			set
			{
				if ((this._SWC_CLLI != value))
				{
					this._SWC_CLLI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOM_SWITCH", DbType="VarChar(11)")]
		public string DOM_SWITCH
		{
			get
			{
				return this._DOM_SWITCH;
			}
			set
			{
				if ((this._DOM_SWITCH != value))
				{
					this._DOM_SWITCH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COORDINATES", DbType="VarChar(MAX)")]
		public string COORDINATES
		{
			get
			{
				return this._COORDINATES;
			}
			set
			{
				if ((this._COORDINATES != value))
				{
					this._COORDINATES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentroidLat", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> CentroidLat
		{
			get
			{
				return this._CentroidLat;
			}
			set
			{
				if ((this._CentroidLat != value))
				{
					this._CentroidLat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentroidLng", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> CentroidLng
		{
			get
			{
				return this._CentroidLng;
			}
			set
			{
				if ((this._CentroidLng != value))
				{
					this._CentroidLng = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="COMET.LATA_CENTROID")]
	public partial class LATA_CENTROID
	{
		
		private short _LATA;
		
		private System.Nullable<double> _CentroidLat;
		
		private System.Nullable<double> _CentroidLng;
		
		public LATA_CENTROID()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATA", DbType="SmallInt NOT NULL")]
		public short LATA
		{
			get
			{
				return this._LATA;
			}
			set
			{
				if ((this._LATA != value))
				{
					this._LATA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentroidLat", DbType="Float")]
		public System.Nullable<double> CentroidLat
		{
			get
			{
				return this._CentroidLat;
			}
			set
			{
				if ((this._CentroidLat != value))
				{
					this._CentroidLat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentroidLng", DbType="Float")]
		public System.Nullable<double> CentroidLng
		{
			get
			{
				return this._CentroidLng;
			}
			set
			{
				if ((this._CentroidLng != value))
				{
					this._CentroidLng = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="COMET.LATA_BOUNDARY_LKP")]
	public partial class LATA_BOUNDARY_LKP
	{
		
		private short _LATA;
		
		private short _POLYGON;
		
		private string _LOCATION;
		
		private string _PROVIDER;
		
		private string _COORDINATES;
		
		public LATA_BOUNDARY_LKP()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATA", DbType="SmallInt NOT NULL")]
		public short LATA
		{
			get
			{
				return this._LATA;
			}
			set
			{
				if ((this._LATA != value))
				{
					this._LATA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POLYGON", DbType="SmallInt NOT NULL")]
		public short POLYGON
		{
			get
			{
				return this._POLYGON;
			}
			set
			{
				if ((this._POLYGON != value))
				{
					this._POLYGON = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION", DbType="VarChar(100)")]
		public string LOCATION
		{
			get
			{
				return this._LOCATION;
			}
			set
			{
				if ((this._LOCATION != value))
				{
					this._LOCATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROVIDER", DbType="VarChar(100)")]
		public string PROVIDER
		{
			get
			{
				return this._PROVIDER;
			}
			set
			{
				if ((this._PROVIDER != value))
				{
					this._PROVIDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COORDINATES", DbType="VarChar(MAX)")]
		public string COORDINATES
		{
			get
			{
				return this._COORDINATES;
			}
			set
			{
				if ((this._COORDINATES != value))
				{
					this._COORDINATES = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="COMET.Level3_RouteMap")]
	public partial class Level3_RouteMap
	{
		
		private int _Polygon;
		
		private string _Coordinates;
		
		public Level3_RouteMap()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Polygon", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Polygon
		{
			get
			{
				return this._Polygon;
			}
			set
			{
				if ((this._Polygon != value))
				{
					this._Polygon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coordinates", DbType="VarChar(MAX)")]
		public string Coordinates
		{
			get
			{
				return this._Coordinates;
			}
			set
			{
				if ((this._Coordinates != value))
				{
					this._Coordinates = value;
				}
			}
		}
	}
	
	public partial class SWC_IN_BOUNDARYResult
	{
		
		private string _SWC_CLLI;
		
		private string _DOM_SWITCH;
		
		private string _COORDINATES;
		
		private System.Nullable<decimal> _CentroidLat;
		
		private System.Nullable<decimal> _CentroidLng;
		
		public SWC_IN_BOUNDARYResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SWC_CLLI", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string SWC_CLLI
		{
			get
			{
				return this._SWC_CLLI;
			}
			set
			{
				if ((this._SWC_CLLI != value))
				{
					this._SWC_CLLI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOM_SWITCH", DbType="VarChar(11)")]
		public string DOM_SWITCH
		{
			get
			{
				return this._DOM_SWITCH;
			}
			set
			{
				if ((this._DOM_SWITCH != value))
				{
					this._DOM_SWITCH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COORDINATES", DbType="VarChar(MAX)")]
		public string COORDINATES
		{
			get
			{
				return this._COORDINATES;
			}
			set
			{
				if ((this._COORDINATES != value))
				{
					this._COORDINATES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentroidLat", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> CentroidLat
		{
			get
			{
				return this._CentroidLat;
			}
			set
			{
				if ((this._CentroidLat != value))
				{
					this._CentroidLat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentroidLng", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> CentroidLng
		{
			get
			{
				return this._CentroidLng;
			}
			set
			{
				if ((this._CentroidLng != value))
				{
					this._CentroidLng = value;
				}
			}
		}
	}
	
	public partial class LATA_IN_BOUNDARYResult
	{
		
		private short _LATA;
		
		private string _COORDINATES;
		
		private System.Nullable<double> _CentroidLat;
		
		private System.Nullable<double> _CentroidLng;
		
		public LATA_IN_BOUNDARYResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATA", DbType="SmallInt NOT NULL")]
		public short LATA
		{
			get
			{
				return this._LATA;
			}
			set
			{
				if ((this._LATA != value))
				{
					this._LATA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COORDINATES", DbType="VarChar(MAX)")]
		public string COORDINATES
		{
			get
			{
				return this._COORDINATES;
			}
			set
			{
				if ((this._COORDINATES != value))
				{
					this._COORDINATES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentroidLat", DbType="Float")]
		public System.Nullable<double> CentroidLat
		{
			get
			{
				return this._CentroidLat;
			}
			set
			{
				if ((this._CentroidLat != value))
				{
					this._CentroidLat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentroidLng", DbType="Float")]
		public System.Nullable<double> CentroidLng
		{
			get
			{
				return this._CentroidLng;
			}
			set
			{
				if ((this._CentroidLng != value))
				{
					this._CentroidLng = value;
				}
			}
		}
	}
	
	public partial class L3FIBER_INBOUNDARY_REDUCEResult
	{
		
		private int _Polygon;
		
		private string _Coordinates;
		
		public L3FIBER_INBOUNDARY_REDUCEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Polygon", DbType="Int NOT NULL")]
		public int Polygon
		{
			get
			{
				return this._Polygon;
			}
			set
			{
				if ((this._Polygon != value))
				{
					this._Polygon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coordinates", DbType="VarChar(MAX)")]
		public string Coordinates
		{
			get
			{
				return this._Coordinates;
			}
			set
			{
				if ((this._Coordinates != value))
				{
					this._Coordinates = value;
				}
			}
		}
	}
	
	public partial class MSO_IN_BOUNDARYResult
	{
		
		private string _CITY;
		
		private string _STATE;
		
		private string _POSTAL_CODE;
		
		private string _Xref_Parent_Vendor;
		
		private string _BOUNDARY_LATLNG;
		
		private System.Nullable<decimal> _CentroidLat;
		
		private System.Nullable<decimal> _CentroidLng;
		
		public MSO_IN_BOUNDARYResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="NVarChar(255)")]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this._CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE", DbType="NVarChar(255)")]
		public string STATE
		{
			get
			{
				return this._STATE;
			}
			set
			{
				if ((this._STATE != value))
				{
					this._STATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTAL_CODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string POSTAL_CODE
		{
			get
			{
				return this._POSTAL_CODE;
			}
			set
			{
				if ((this._POSTAL_CODE != value))
				{
					this._POSTAL_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Xref_Parent_Vendor", DbType="NVarChar(255)")]
		public string Xref_Parent_Vendor
		{
			get
			{
				return this._Xref_Parent_Vendor;
			}
			set
			{
				if ((this._Xref_Parent_Vendor != value))
				{
					this._Xref_Parent_Vendor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BOUNDARY_LATLNG", DbType="VarChar(800)")]
		public string BOUNDARY_LATLNG
		{
			get
			{
				return this._BOUNDARY_LATLNG;
			}
			set
			{
				if ((this._BOUNDARY_LATLNG != value))
				{
					this._BOUNDARY_LATLNG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentroidLat", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> CentroidLat
		{
			get
			{
				return this._CentroidLat;
			}
			set
			{
				if ((this._CentroidLat != value))
				{
					this._CentroidLat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentroidLng", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> CentroidLng
		{
			get
			{
				return this._CentroidLng;
			}
			set
			{
				if ((this._CentroidLng != value))
				{
					this._CentroidLng = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
