#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMET.Server.Domain
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GAM_Complex_Op")]
	public partial class BulkDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertZ_BULK_FROM_EXCEL_STAGE(Z_BULK_FROM_EXCEL_STAGE instance);
    partial void UpdateZ_BULK_FROM_EXCEL_STAGE(Z_BULK_FROM_EXCEL_STAGE instance);
    partial void DeleteZ_BULK_FROM_EXCEL_STAGE(Z_BULK_FROM_EXCEL_STAGE instance);
    partial void InsertBULK_ADDRESS_HISTORICAL(BULK_ADDRESS_HISTORICAL instance);
    partial void UpdateBULK_ADDRESS_HISTORICAL(BULK_ADDRESS_HISTORICAL instance);
    partial void DeleteBULK_ADDRESS_HISTORICAL(BULK_ADDRESS_HISTORICAL instance);
    #endregion
		
		public BulkDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BulkDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BulkDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BulkDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Z_BULK_FROM_EXCEL_STAGE> Z_BULK_FROM_EXCEL_STAGEs
		{
			get
			{
				return this.GetTable<Z_BULK_FROM_EXCEL_STAGE>();
			}
		}
		
		public System.Data.Linq.Table<BULK_ADDRESS_HISTORICAL> BULK_ADDRESS_HISTORICALs
		{
			get
			{
				return this.GetTable<BULK_ADDRESS_HISTORICAL>();
			}
		}
		
		public System.Data.Linq.Table<VENDORS_BY_CLLI> VENDORS_BY_CLLIs
		{
			get
			{
				return this.GetTable<VENDORS_BY_CLLI>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="COMET.BULK_EXCEL_IMPORT")]
		public int BULK_EXCEL_IMPORT([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Distance", DbType="Decimal(5,2)")] System.Nullable<decimal> distance, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TopCount", DbType="Int")] System.Nullable<int> topCount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RequestID", DbType="Int")] System.Nullable<int> requestID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmployeeID", DbType="Int")] System.Nullable<int> employeeID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), distance, topCount, requestID, employeeID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="COMET.VENDORS_BY_CLLI")]
		public ISingleResult<VENDORS_BY_CLLI> VENDORS_BY_CLLI([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClliString", DbType="VarChar(MAX)")] string clliString, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Distance", DbType="Decimal(6,3)")] System.Nullable<decimal> distance, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TopCount", DbType="Int")] System.Nullable<int> topCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clliString, distance, topCount);
			return ((ISingleResult<VENDORS_BY_CLLI>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="COMET.Z_BULK_FROM_EXCEL_STAGE")]
	public partial class Z_BULK_FROM_EXCEL_STAGE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _reference_id;
		
		private string _bldg_clli;
		
		private string _swc_clli;
		
		private string _npa;
		
		private string _nxx;
		
		private string _address;
		
		private string _city;
		
		private string _state_code;
		
		private string _postal_code;
		
		private string _product;
		
		private string _service_type;
		
		private string _transaction_type;
		
		private string _NNI_vendor;
		
		private string _service_bandwidth_CP_port_speed;
		
		private string _form_factor;
		
		private System.Nullable<int> _EVC;
		
		private System.Nullable<int> _service_term;
		
		private string _class_of_service;
		
		private string _solution_type;
		
		private string _include_avoid_single_vendor;
		
		private System.Nullable<int> _max_sol;
		
		private string _country_code;
		
		private System.Nullable<char> _protection;
		
		private System.Nullable<char> _co_termination;
		
		private System.Nullable<char> _avoid_override_term;
		
		private System.Nullable<char> _include_unapproved_ilec;
		
		private System.Nullable<int> _max_asr;
		
		private System.Nullable<char> _avoid_typeII;
		
		private int _RequestID;
		
		private System.Nullable<decimal> _GoogleLat;
		
		private System.Nullable<decimal> _GoogleLng;
		
		private System.Nullable<System.DateTime> _RequestDateTime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onreference_idChanging(int value);
    partial void Onreference_idChanged();
    partial void Onbldg_clliChanging(string value);
    partial void Onbldg_clliChanged();
    partial void Onswc_clliChanging(string value);
    partial void Onswc_clliChanged();
    partial void OnnpaChanging(string value);
    partial void OnnpaChanged();
    partial void OnnxxChanging(string value);
    partial void OnnxxChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void Onstate_codeChanging(string value);
    partial void Onstate_codeChanged();
    partial void Onpostal_codeChanging(string value);
    partial void Onpostal_codeChanged();
    partial void OnproductChanging(string value);
    partial void OnproductChanged();
    partial void Onservice_typeChanging(string value);
    partial void Onservice_typeChanged();
    partial void Ontransaction_typeChanging(string value);
    partial void Ontransaction_typeChanged();
    partial void OnNNI_vendorChanging(string value);
    partial void OnNNI_vendorChanged();
    partial void Onservice_bandwidth_CP_port_speedChanging(string value);
    partial void Onservice_bandwidth_CP_port_speedChanged();
    partial void Onform_factorChanging(string value);
    partial void Onform_factorChanged();
    partial void OnEVCChanging(System.Nullable<int> value);
    partial void OnEVCChanged();
    partial void Onservice_termChanging(System.Nullable<int> value);
    partial void Onservice_termChanged();
    partial void Onclass_of_serviceChanging(string value);
    partial void Onclass_of_serviceChanged();
    partial void Onsolution_typeChanging(string value);
    partial void Onsolution_typeChanged();
    partial void Oninclude_avoid_single_vendorChanging(string value);
    partial void Oninclude_avoid_single_vendorChanged();
    partial void Onmax_solChanging(System.Nullable<int> value);
    partial void Onmax_solChanged();
    partial void Oncountry_codeChanging(string value);
    partial void Oncountry_codeChanged();
    partial void OnprotectionChanging(System.Nullable<char> value);
    partial void OnprotectionChanged();
    partial void Onco_terminationChanging(System.Nullable<char> value);
    partial void Onco_terminationChanged();
    partial void Onavoid_override_termChanging(System.Nullable<char> value);
    partial void Onavoid_override_termChanged();
    partial void Oninclude_unapproved_ilecChanging(System.Nullable<char> value);
    partial void Oninclude_unapproved_ilecChanged();
    partial void Onmax_asrChanging(System.Nullable<int> value);
    partial void Onmax_asrChanged();
    partial void Onavoid_typeIIChanging(System.Nullable<char> value);
    partial void Onavoid_typeIIChanged();
    partial void OnRequestIDChanging(int value);
    partial void OnRequestIDChanged();
    partial void OnGoogleLatChanging(System.Nullable<decimal> value);
    partial void OnGoogleLatChanged();
    partial void OnGoogleLngChanging(System.Nullable<decimal> value);
    partial void OnGoogleLngChanged();
    partial void OnRequestDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnRequestDateTimeChanged();
    #endregion
		
		public Z_BULK_FROM_EXCEL_STAGE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reference_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int reference_id
		{
			get
			{
				return this._reference_id;
			}
			set
			{
				if ((this._reference_id != value))
				{
					this.Onreference_idChanging(value);
					this.SendPropertyChanging();
					this._reference_id = value;
					this.SendPropertyChanged("reference_id");
					this.Onreference_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bldg_clli", DbType="VarChar(8)")]
		public string bldg_clli
		{
			get
			{
				return this._bldg_clli;
			}
			set
			{
				if ((this._bldg_clli != value))
				{
					this.Onbldg_clliChanging(value);
					this.SendPropertyChanging();
					this._bldg_clli = value;
					this.SendPropertyChanged("bldg_clli");
					this.Onbldg_clliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_swc_clli", DbType="VarChar(8)")]
		public string swc_clli
		{
			get
			{
				return this._swc_clli;
			}
			set
			{
				if ((this._swc_clli != value))
				{
					this.Onswc_clliChanging(value);
					this.SendPropertyChanging();
					this._swc_clli = value;
					this.SendPropertyChanged("swc_clli");
					this.Onswc_clliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_npa", DbType="VarChar(500)")]
		public string npa
		{
			get
			{
				return this._npa;
			}
			set
			{
				if ((this._npa != value))
				{
					this.OnnpaChanging(value);
					this.SendPropertyChanging();
					this._npa = value;
					this.SendPropertyChanged("npa");
					this.OnnpaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nxx", DbType="VarChar(500)")]
		public string nxx
		{
			get
			{
				return this._nxx;
			}
			set
			{
				if ((this._nxx != value))
				{
					this.OnnxxChanging(value);
					this.SendPropertyChanging();
					this._nxx = value;
					this.SendPropertyChanged("nxx");
					this.OnnxxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(2000)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(500)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_code", DbType="VarChar(2)")]
		public string state_code
		{
			get
			{
				return this._state_code;
			}
			set
			{
				if ((this._state_code != value))
				{
					this.Onstate_codeChanging(value);
					this.SendPropertyChanging();
					this._state_code = value;
					this.SendPropertyChanged("state_code");
					this.Onstate_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postal_code", DbType="VarChar(9)")]
		public string postal_code
		{
			get
			{
				return this._postal_code;
			}
			set
			{
				if ((this._postal_code != value))
				{
					this.Onpostal_codeChanging(value);
					this.SendPropertyChanging();
					this._postal_code = value;
					this.SendPropertyChanged("postal_code");
					this.Onpostal_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product", DbType="VarChar(500)")]
		public string product
		{
			get
			{
				return this._product;
			}
			set
			{
				if ((this._product != value))
				{
					this.OnproductChanging(value);
					this.SendPropertyChanging();
					this._product = value;
					this.SendPropertyChanged("product");
					this.OnproductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_service_type", DbType="VarChar(500)")]
		public string service_type
		{
			get
			{
				return this._service_type;
			}
			set
			{
				if ((this._service_type != value))
				{
					this.Onservice_typeChanging(value);
					this.SendPropertyChanging();
					this._service_type = value;
					this.SendPropertyChanged("service_type");
					this.Onservice_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transaction_type", DbType="VarChar(500)")]
		public string transaction_type
		{
			get
			{
				return this._transaction_type;
			}
			set
			{
				if ((this._transaction_type != value))
				{
					this.Ontransaction_typeChanging(value);
					this.SendPropertyChanging();
					this._transaction_type = value;
					this.SendPropertyChanged("transaction_type");
					this.Ontransaction_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI_vendor", DbType="VarChar(500)")]
		public string NNI_vendor
		{
			get
			{
				return this._NNI_vendor;
			}
			set
			{
				if ((this._NNI_vendor != value))
				{
					this.OnNNI_vendorChanging(value);
					this.SendPropertyChanging();
					this._NNI_vendor = value;
					this.SendPropertyChanged("NNI_vendor");
					this.OnNNI_vendorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[service_bandwidth/CP_port_speed]", Storage="_service_bandwidth_CP_port_speed", DbType="VarChar(500)")]
		public string service_bandwidth_CP_port_speed
		{
			get
			{
				return this._service_bandwidth_CP_port_speed;
			}
			set
			{
				if ((this._service_bandwidth_CP_port_speed != value))
				{
					this.Onservice_bandwidth_CP_port_speedChanging(value);
					this.SendPropertyChanging();
					this._service_bandwidth_CP_port_speed = value;
					this.SendPropertyChanged("service_bandwidth_CP_port_speed");
					this.Onservice_bandwidth_CP_port_speedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_form_factor", DbType="VarChar(500)")]
		public string form_factor
		{
			get
			{
				return this._form_factor;
			}
			set
			{
				if ((this._form_factor != value))
				{
					this.Onform_factorChanging(value);
					this.SendPropertyChanging();
					this._form_factor = value;
					this.SendPropertyChanged("form_factor");
					this.Onform_factorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVC", DbType="Int")]
		public System.Nullable<int> EVC
		{
			get
			{
				return this._EVC;
			}
			set
			{
				if ((this._EVC != value))
				{
					this.OnEVCChanging(value);
					this.SendPropertyChanging();
					this._EVC = value;
					this.SendPropertyChanged("EVC");
					this.OnEVCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_service_term", DbType="Int")]
		public System.Nullable<int> service_term
		{
			get
			{
				return this._service_term;
			}
			set
			{
				if ((this._service_term != value))
				{
					this.Onservice_termChanging(value);
					this.SendPropertyChanging();
					this._service_term = value;
					this.SendPropertyChanged("service_term");
					this.Onservice_termChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_class_of_service", DbType="VarChar(500)")]
		public string class_of_service
		{
			get
			{
				return this._class_of_service;
			}
			set
			{
				if ((this._class_of_service != value))
				{
					this.Onclass_of_serviceChanging(value);
					this.SendPropertyChanging();
					this._class_of_service = value;
					this.SendPropertyChanged("class_of_service");
					this.Onclass_of_serviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_solution_type", DbType="VarChar(500)")]
		public string solution_type
		{
			get
			{
				return this._solution_type;
			}
			set
			{
				if ((this._solution_type != value))
				{
					this.Onsolution_typeChanging(value);
					this.SendPropertyChanging();
					this._solution_type = value;
					this.SendPropertyChanged("solution_type");
					this.Onsolution_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_include_avoid_single_vendor", DbType="VarChar(500)")]
		public string include_avoid_single_vendor
		{
			get
			{
				return this._include_avoid_single_vendor;
			}
			set
			{
				if ((this._include_avoid_single_vendor != value))
				{
					this.Oninclude_avoid_single_vendorChanging(value);
					this.SendPropertyChanging();
					this._include_avoid_single_vendor = value;
					this.SendPropertyChanged("include_avoid_single_vendor");
					this.Oninclude_avoid_single_vendorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max_sol", DbType="Int")]
		public System.Nullable<int> max_sol
		{
			get
			{
				return this._max_sol;
			}
			set
			{
				if ((this._max_sol != value))
				{
					this.Onmax_solChanging(value);
					this.SendPropertyChanging();
					this._max_sol = value;
					this.SendPropertyChanged("max_sol");
					this.Onmax_solChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_code", DbType="VarChar(2)")]
		public string country_code
		{
			get
			{
				return this._country_code;
			}
			set
			{
				if ((this._country_code != value))
				{
					this.Oncountry_codeChanging(value);
					this.SendPropertyChanging();
					this._country_code = value;
					this.SendPropertyChanged("country_code");
					this.Oncountry_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_protection", DbType="Char(1)")]
		public System.Nullable<char> protection
		{
			get
			{
				return this._protection;
			}
			set
			{
				if ((this._protection != value))
				{
					this.OnprotectionChanging(value);
					this.SendPropertyChanging();
					this._protection = value;
					this.SendPropertyChanged("protection");
					this.OnprotectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_co_termination", DbType="Char(1)")]
		public System.Nullable<char> co_termination
		{
			get
			{
				return this._co_termination;
			}
			set
			{
				if ((this._co_termination != value))
				{
					this.Onco_terminationChanging(value);
					this.SendPropertyChanging();
					this._co_termination = value;
					this.SendPropertyChanged("co_termination");
					this.Onco_terminationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avoid_override_term", DbType="Char(1)")]
		public System.Nullable<char> avoid_override_term
		{
			get
			{
				return this._avoid_override_term;
			}
			set
			{
				if ((this._avoid_override_term != value))
				{
					this.Onavoid_override_termChanging(value);
					this.SendPropertyChanging();
					this._avoid_override_term = value;
					this.SendPropertyChanged("avoid_override_term");
					this.Onavoid_override_termChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_include_unapproved_ilec", DbType="Char(1)")]
		public System.Nullable<char> include_unapproved_ilec
		{
			get
			{
				return this._include_unapproved_ilec;
			}
			set
			{
				if ((this._include_unapproved_ilec != value))
				{
					this.Oninclude_unapproved_ilecChanging(value);
					this.SendPropertyChanging();
					this._include_unapproved_ilec = value;
					this.SendPropertyChanged("include_unapproved_ilec");
					this.Oninclude_unapproved_ilecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max_asr", DbType="Int")]
		public System.Nullable<int> max_asr
		{
			get
			{
				return this._max_asr;
			}
			set
			{
				if ((this._max_asr != value))
				{
					this.Onmax_asrChanging(value);
					this.SendPropertyChanging();
					this._max_asr = value;
					this.SendPropertyChanged("max_asr");
					this.Onmax_asrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avoid_typeII", DbType="Char(1)")]
		public System.Nullable<char> avoid_typeII
		{
			get
			{
				return this._avoid_typeII;
			}
			set
			{
				if ((this._avoid_typeII != value))
				{
					this.Onavoid_typeIIChanging(value);
					this.SendPropertyChanging();
					this._avoid_typeII = value;
					this.SendPropertyChanged("avoid_typeII");
					this.Onavoid_typeIIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int RequestID
		{
			get
			{
				return this._RequestID;
			}
			set
			{
				if ((this._RequestID != value))
				{
					this.OnRequestIDChanging(value);
					this.SendPropertyChanging();
					this._RequestID = value;
					this.SendPropertyChanged("RequestID");
					this.OnRequestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoogleLat", DbType="Decimal(10,7)")]
		public System.Nullable<decimal> GoogleLat
		{
			get
			{
				return this._GoogleLat;
			}
			set
			{
				if ((this._GoogleLat != value))
				{
					this.OnGoogleLatChanging(value);
					this.SendPropertyChanging();
					this._GoogleLat = value;
					this.SendPropertyChanged("GoogleLat");
					this.OnGoogleLatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoogleLng", DbType="Decimal(10,7)")]
		public System.Nullable<decimal> GoogleLng
		{
			get
			{
				return this._GoogleLng;
			}
			set
			{
				if ((this._GoogleLng != value))
				{
					this.OnGoogleLngChanging(value);
					this.SendPropertyChanging();
					this._GoogleLng = value;
					this.SendPropertyChanged("GoogleLng");
					this.OnGoogleLngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> RequestDateTime
		{
			get
			{
				return this._RequestDateTime;
			}
			set
			{
				if ((this._RequestDateTime != value))
				{
					this.OnRequestDateTimeChanging(value);
					this.SendPropertyChanging();
					this._RequestDateTime = value;
					this.SendPropertyChanged("RequestDateTime");
					this.OnRequestDateTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="COMET.BULK_ADDRESS_HISTORICAL")]
	public partial class BULK_ADDRESS_HISTORICAL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RequestID;
		
		private int _reference_id;
		
		private int _returnKey;
		
		private System.Nullable<short> _LATA;
		
		private string _RequestAddress;
		
		private string _RequestCity;
		
		private string _RequestState;
		
		private string _RequestPostalCode;
		
		private System.Nullable<decimal> _RequestLat;
		
		private System.Nullable<decimal> _RequestLng;
		
		private string _MSOVendor;
		
		private string _MSOAddress;
		
		private string _MSOCity;
		
		private string _MSOState;
		
		private string _CLECVendor;
		
		private string _CLECType;
		
		private string _CLECAddress;
		
		private string _CLECCity;
		
		private string _CLECState;
		
		private System.Nullable<decimal> _Distance;
		
		private System.Nullable<int> _EntityLineItemID;
		
		private string _BandwidthDesc;
		
		private string _ProductDesc;
		
		private System.Nullable<decimal> _mrUSD;
		
		private string _Vendor;
		
		private System.Nullable<decimal> _IncrementalNRCost;
		
		private string _StreetAddress;
		
		private string _City;
		
		private string _State;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRequestIDChanging(int value);
    partial void OnRequestIDChanged();
    partial void Onreference_idChanging(int value);
    partial void Onreference_idChanged();
    partial void OnreturnKeyChanging(int value);
    partial void OnreturnKeyChanged();
    partial void OnLATAChanging(System.Nullable<short> value);
    partial void OnLATAChanged();
    partial void OnRequestAddressChanging(string value);
    partial void OnRequestAddressChanged();
    partial void OnRequestCityChanging(string value);
    partial void OnRequestCityChanged();
    partial void OnRequestStateChanging(string value);
    partial void OnRequestStateChanged();
    partial void OnRequestPostalCodeChanging(string value);
    partial void OnRequestPostalCodeChanged();
    partial void OnRequestLatChanging(System.Nullable<decimal> value);
    partial void OnRequestLatChanged();
    partial void OnRequestLngChanging(System.Nullable<decimal> value);
    partial void OnRequestLngChanged();
    partial void OnMSOVendorChanging(string value);
    partial void OnMSOVendorChanged();
    partial void OnMSOAddressChanging(string value);
    partial void OnMSOAddressChanged();
    partial void OnMSOCityChanging(string value);
    partial void OnMSOCityChanged();
    partial void OnMSOStateChanging(string value);
    partial void OnMSOStateChanged();
    partial void OnCLECVendorChanging(string value);
    partial void OnCLECVendorChanged();
    partial void OnCLECTypeChanging(string value);
    partial void OnCLECTypeChanged();
    partial void OnCLECAddressChanging(string value);
    partial void OnCLECAddressChanged();
    partial void OnCLECCityChanging(string value);
    partial void OnCLECCityChanged();
    partial void OnCLECStateChanging(string value);
    partial void OnCLECStateChanged();
    partial void OnDistanceChanging(System.Nullable<decimal> value);
    partial void OnDistanceChanged();
    partial void OnEntityLineItemIDChanging(System.Nullable<int> value);
    partial void OnEntityLineItemIDChanged();
    partial void OnBandwidthDescChanging(string value);
    partial void OnBandwidthDescChanged();
    partial void OnProductDescChanging(string value);
    partial void OnProductDescChanged();
    partial void OnmrUSDChanging(System.Nullable<decimal> value);
    partial void OnmrUSDChanged();
    partial void OnVendorChanging(string value);
    partial void OnVendorChanged();
    partial void OnIncrementalNRCostChanging(System.Nullable<decimal> value);
    partial void OnIncrementalNRCostChanged();
    partial void OnStreetAddressChanging(string value);
    partial void OnStreetAddressChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    #endregion
		
		public BULK_ADDRESS_HISTORICAL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int RequestID
		{
			get
			{
				return this._RequestID;
			}
			set
			{
				if ((this._RequestID != value))
				{
					this.OnRequestIDChanging(value);
					this.SendPropertyChanging();
					this._RequestID = value;
					this.SendPropertyChanged("RequestID");
					this.OnRequestIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reference_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int reference_id
		{
			get
			{
				return this._reference_id;
			}
			set
			{
				if ((this._reference_id != value))
				{
					this.Onreference_idChanging(value);
					this.SendPropertyChanging();
					this._reference_id = value;
					this.SendPropertyChanged("reference_id");
					this.Onreference_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_returnKey", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int returnKey
		{
			get
			{
				return this._returnKey;
			}
			set
			{
				if ((this._returnKey != value))
				{
					this.OnreturnKeyChanging(value);
					this.SendPropertyChanging();
					this._returnKey = value;
					this.SendPropertyChanged("returnKey");
					this.OnreturnKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATA", DbType="SmallInt")]
		public System.Nullable<short> LATA
		{
			get
			{
				return this._LATA;
			}
			set
			{
				if ((this._LATA != value))
				{
					this.OnLATAChanging(value);
					this.SendPropertyChanging();
					this._LATA = value;
					this.SendPropertyChanged("LATA");
					this.OnLATAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestAddress", DbType="VarChar(250)")]
		public string RequestAddress
		{
			get
			{
				return this._RequestAddress;
			}
			set
			{
				if ((this._RequestAddress != value))
				{
					this.OnRequestAddressChanging(value);
					this.SendPropertyChanging();
					this._RequestAddress = value;
					this.SendPropertyChanged("RequestAddress");
					this.OnRequestAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestCity", DbType="VarChar(100)")]
		public string RequestCity
		{
			get
			{
				return this._RequestCity;
			}
			set
			{
				if ((this._RequestCity != value))
				{
					this.OnRequestCityChanging(value);
					this.SendPropertyChanging();
					this._RequestCity = value;
					this.SendPropertyChanged("RequestCity");
					this.OnRequestCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestState", DbType="VarChar(50)")]
		public string RequestState
		{
			get
			{
				return this._RequestState;
			}
			set
			{
				if ((this._RequestState != value))
				{
					this.OnRequestStateChanging(value);
					this.SendPropertyChanging();
					this._RequestState = value;
					this.SendPropertyChanged("RequestState");
					this.OnRequestStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestPostalCode", DbType="VarChar(10)")]
		public string RequestPostalCode
		{
			get
			{
				return this._RequestPostalCode;
			}
			set
			{
				if ((this._RequestPostalCode != value))
				{
					this.OnRequestPostalCodeChanging(value);
					this.SendPropertyChanging();
					this._RequestPostalCode = value;
					this.SendPropertyChanged("RequestPostalCode");
					this.OnRequestPostalCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestLat", DbType="Decimal(10,7)")]
		public System.Nullable<decimal> RequestLat
		{
			get
			{
				return this._RequestLat;
			}
			set
			{
				if ((this._RequestLat != value))
				{
					this.OnRequestLatChanging(value);
					this.SendPropertyChanging();
					this._RequestLat = value;
					this.SendPropertyChanged("RequestLat");
					this.OnRequestLatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestLng", DbType="Decimal(10,7)")]
		public System.Nullable<decimal> RequestLng
		{
			get
			{
				return this._RequestLng;
			}
			set
			{
				if ((this._RequestLng != value))
				{
					this.OnRequestLngChanging(value);
					this.SendPropertyChanging();
					this._RequestLng = value;
					this.SendPropertyChanged("RequestLng");
					this.OnRequestLngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSOVendor", DbType="VarChar(50)")]
		public string MSOVendor
		{
			get
			{
				return this._MSOVendor;
			}
			set
			{
				if ((this._MSOVendor != value))
				{
					this.OnMSOVendorChanging(value);
					this.SendPropertyChanging();
					this._MSOVendor = value;
					this.SendPropertyChanged("MSOVendor");
					this.OnMSOVendorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSOAddress", DbType="VarChar(250)")]
		public string MSOAddress
		{
			get
			{
				return this._MSOAddress;
			}
			set
			{
				if ((this._MSOAddress != value))
				{
					this.OnMSOAddressChanging(value);
					this.SendPropertyChanging();
					this._MSOAddress = value;
					this.SendPropertyChanged("MSOAddress");
					this.OnMSOAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSOCity", DbType="VarChar(100)")]
		public string MSOCity
		{
			get
			{
				return this._MSOCity;
			}
			set
			{
				if ((this._MSOCity != value))
				{
					this.OnMSOCityChanging(value);
					this.SendPropertyChanging();
					this._MSOCity = value;
					this.SendPropertyChanged("MSOCity");
					this.OnMSOCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSOState", DbType="VarChar(50)")]
		public string MSOState
		{
			get
			{
				return this._MSOState;
			}
			set
			{
				if ((this._MSOState != value))
				{
					this.OnMSOStateChanging(value);
					this.SendPropertyChanging();
					this._MSOState = value;
					this.SendPropertyChanged("MSOState");
					this.OnMSOStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLECVendor", DbType="VarChar(50)")]
		public string CLECVendor
		{
			get
			{
				return this._CLECVendor;
			}
			set
			{
				if ((this._CLECVendor != value))
				{
					this.OnCLECVendorChanging(value);
					this.SendPropertyChanging();
					this._CLECVendor = value;
					this.SendPropertyChanged("CLECVendor");
					this.OnCLECVendorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLECType", DbType="VarChar(25)")]
		public string CLECType
		{
			get
			{
				return this._CLECType;
			}
			set
			{
				if ((this._CLECType != value))
				{
					this.OnCLECTypeChanging(value);
					this.SendPropertyChanging();
					this._CLECType = value;
					this.SendPropertyChanged("CLECType");
					this.OnCLECTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLECAddress", DbType="VarChar(250)")]
		public string CLECAddress
		{
			get
			{
				return this._CLECAddress;
			}
			set
			{
				if ((this._CLECAddress != value))
				{
					this.OnCLECAddressChanging(value);
					this.SendPropertyChanging();
					this._CLECAddress = value;
					this.SendPropertyChanged("CLECAddress");
					this.OnCLECAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLECCity", DbType="VarChar(100)")]
		public string CLECCity
		{
			get
			{
				return this._CLECCity;
			}
			set
			{
				if ((this._CLECCity != value))
				{
					this.OnCLECCityChanging(value);
					this.SendPropertyChanging();
					this._CLECCity = value;
					this.SendPropertyChanged("CLECCity");
					this.OnCLECCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLECState", DbType="VarChar(50)")]
		public string CLECState
		{
			get
			{
				return this._CLECState;
			}
			set
			{
				if ((this._CLECState != value))
				{
					this.OnCLECStateChanging(value);
					this.SendPropertyChanging();
					this._CLECState = value;
					this.SendPropertyChanged("CLECState");
					this.OnCLECStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distance", DbType="Decimal(10,7)")]
		public System.Nullable<decimal> Distance
		{
			get
			{
				return this._Distance;
			}
			set
			{
				if ((this._Distance != value))
				{
					this.OnDistanceChanging(value);
					this.SendPropertyChanging();
					this._Distance = value;
					this.SendPropertyChanged("Distance");
					this.OnDistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntityLineItemID", DbType="Int")]
		public System.Nullable<int> EntityLineItemID
		{
			get
			{
				return this._EntityLineItemID;
			}
			set
			{
				if ((this._EntityLineItemID != value))
				{
					this.OnEntityLineItemIDChanging(value);
					this.SendPropertyChanging();
					this._EntityLineItemID = value;
					this.SendPropertyChanged("EntityLineItemID");
					this.OnEntityLineItemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BandwidthDesc", DbType="VarChar(100)")]
		public string BandwidthDesc
		{
			get
			{
				return this._BandwidthDesc;
			}
			set
			{
				if ((this._BandwidthDesc != value))
				{
					this.OnBandwidthDescChanging(value);
					this.SendPropertyChanging();
					this._BandwidthDesc = value;
					this.SendPropertyChanged("BandwidthDesc");
					this.OnBandwidthDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductDesc", DbType="VarChar(100)")]
		public string ProductDesc
		{
			get
			{
				return this._ProductDesc;
			}
			set
			{
				if ((this._ProductDesc != value))
				{
					this.OnProductDescChanging(value);
					this.SendPropertyChanging();
					this._ProductDesc = value;
					this.SendPropertyChanged("ProductDesc");
					this.OnProductDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mrUSD", DbType="Money")]
		public System.Nullable<decimal> mrUSD
		{
			get
			{
				return this._mrUSD;
			}
			set
			{
				if ((this._mrUSD != value))
				{
					this.OnmrUSDChanging(value);
					this.SendPropertyChanging();
					this._mrUSD = value;
					this.SendPropertyChanged("mrUSD");
					this.OnmrUSDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vendor", DbType="VarChar(1000)")]
		public string Vendor
		{
			get
			{
				return this._Vendor;
			}
			set
			{
				if ((this._Vendor != value))
				{
					this.OnVendorChanging(value);
					this.SendPropertyChanging();
					this._Vendor = value;
					this.SendPropertyChanged("Vendor");
					this.OnVendorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IncrementalNRCost", DbType="Money")]
		public System.Nullable<decimal> IncrementalNRCost
		{
			get
			{
				return this._IncrementalNRCost;
			}
			set
			{
				if ((this._IncrementalNRCost != value))
				{
					this.OnIncrementalNRCostChanging(value);
					this.SendPropertyChanging();
					this._IncrementalNRCost = value;
					this.SendPropertyChanged("IncrementalNRCost");
					this.OnIncrementalNRCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetAddress", DbType="NVarChar(305)")]
		public string StreetAddress
		{
			get
			{
				return this._StreetAddress;
			}
			set
			{
				if ((this._StreetAddress != value))
				{
					this.OnStreetAddressChanging(value);
					this.SendPropertyChanging();
					this._StreetAddress = value;
					this.SendPropertyChanged("StreetAddress");
					this.OnStreetAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(100)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(50)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class VENDORS_BY_CLLI
	{
		
		private string _LATA;
		
		private string _EnteredClli;
		
		private string _EnteredStreet;
		
		private string _EnteredCity;
		
		private string _EnteredState;
		
		private decimal _EnteredLat;
		
		private decimal _EnteredLng;
		
		private string _Vendor;
		
		private string _VendorType;
		
		private string _AddressClli;
		
		private string _VendorStreet;
		
		private string _VendorCity;
		
		private string _VendorState;
		
		private decimal _VendorLat;
		
		private decimal _VendorLng;
		
		private decimal _Miles;
		
		public VENDORS_BY_CLLI()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATA", CanBeNull=false)]
		public string LATA
		{
			get
			{
				return this._LATA;
			}
			set
			{
				if ((this._LATA != value))
				{
					this._LATA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnteredClli", CanBeNull=false)]
		public string EnteredClli
		{
			get
			{
				return this._EnteredClli;
			}
			set
			{
				if ((this._EnteredClli != value))
				{
					this._EnteredClli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnteredStreet", CanBeNull=false)]
		public string EnteredStreet
		{
			get
			{
				return this._EnteredStreet;
			}
			set
			{
				if ((this._EnteredStreet != value))
				{
					this._EnteredStreet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnteredCity", CanBeNull=false)]
		public string EnteredCity
		{
			get
			{
				return this._EnteredCity;
			}
			set
			{
				if ((this._EnteredCity != value))
				{
					this._EnteredCity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnteredState", CanBeNull=false)]
		public string EnteredState
		{
			get
			{
				return this._EnteredState;
			}
			set
			{
				if ((this._EnteredState != value))
				{
					this._EnteredState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnteredLat")]
		public decimal EnteredLat
		{
			get
			{
				return this._EnteredLat;
			}
			set
			{
				if ((this._EnteredLat != value))
				{
					this._EnteredLat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnteredLng")]
		public decimal EnteredLng
		{
			get
			{
				return this._EnteredLng;
			}
			set
			{
				if ((this._EnteredLng != value))
				{
					this._EnteredLng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vendor", CanBeNull=false)]
		public string Vendor
		{
			get
			{
				return this._Vendor;
			}
			set
			{
				if ((this._Vendor != value))
				{
					this._Vendor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorType", CanBeNull=false)]
		public string VendorType
		{
			get
			{
				return this._VendorType;
			}
			set
			{
				if ((this._VendorType != value))
				{
					this._VendorType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressClli", CanBeNull=false)]
		public string AddressClli
		{
			get
			{
				return this._AddressClli;
			}
			set
			{
				if ((this._AddressClli != value))
				{
					this._AddressClli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorStreet", CanBeNull=false)]
		public string VendorStreet
		{
			get
			{
				return this._VendorStreet;
			}
			set
			{
				if ((this._VendorStreet != value))
				{
					this._VendorStreet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorCity", CanBeNull=false)]
		public string VendorCity
		{
			get
			{
				return this._VendorCity;
			}
			set
			{
				if ((this._VendorCity != value))
				{
					this._VendorCity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorState", CanBeNull=false)]
		public string VendorState
		{
			get
			{
				return this._VendorState;
			}
			set
			{
				if ((this._VendorState != value))
				{
					this._VendorState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorLat")]
		public decimal VendorLat
		{
			get
			{
				return this._VendorLat;
			}
			set
			{
				if ((this._VendorLat != value))
				{
					this._VendorLat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorLng")]
		public decimal VendorLng
		{
			get
			{
				return this._VendorLng;
			}
			set
			{
				if ((this._VendorLng != value))
				{
					this._VendorLng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Miles")]
		public decimal Miles
		{
			get
			{
				return this._Miles;
			}
			set
			{
				if ((this._Miles != value))
				{
					this._Miles = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
