#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMET.Server.Domain
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GAM_Complex_Op")]
	public partial class LocationsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEF_TRAIL(EF_TRAIL instance);
    partial void UpdateEF_TRAIL(EF_TRAIL instance);
    partial void DeleteEF_TRAIL(EF_TRAIL instance);
    partial void InsertSDP_TREND(SDP_TREND instance);
    partial void UpdateSDP_TREND(SDP_TREND instance);
    partial void DeleteSDP_TREND(SDP_TREND instance);
    #endregion
		
		public LocationsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LocationsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LocationsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LocationsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ADDRESSES_VW> ADDRESSES_VWs
		{
			get
			{
				return this.GetTable<ADDRESSES_VW>();
			}
		}
		
		public System.Data.Linq.Table<ILEC_LOOKUP_VW> ILEC_LOOKUP_VWs
		{
			get
			{
				return this.GetTable<ILEC_LOOKUP_VW>();
			}
		}
		
		public System.Data.Linq.Table<EF_TRAIL> EF_TRAILs
		{
			get
			{
				return this.GetTable<EF_TRAIL>();
			}
		}
		
		public System.Data.Linq.Table<SDP_ALL> SDP_ALLs
		{
			get
			{
				return this.GetTable<SDP_ALL>();
			}
		}
		
		public System.Data.Linq.Table<SDP_TREND> SDP_TRENDs
		{
			get
			{
				return this.GetTable<SDP_TREND>();
			}
		}
		
		public System.Data.Linq.Table<ClecByMiles> ClecByMiles
		{
			get
			{
				return this.GetTable<ClecByMiles>();
			}
		}
		
		public System.Data.Linq.Table<T_NNI_FAC> T_NNI_FACs
		{
			get
			{
				return this.GetTable<T_NNI_FAC>();
			}
		}
		
		public System.Data.Linq.Table<LOCATION_ASSET> LOCATION_ASSETs
		{
			get
			{
				return this.GetTable<LOCATION_ASSET>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="COMET.SDP_TREND_PIVOT")]
		public ISingleResult<SDP_TREND> SDP_TREND_PIVOT([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Weeks", DbType="Int")] System.Nullable<int> weeks)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), weeks);
			return ((ISingleResult<SDP_TREND>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="COMET.CLEC_MILES")]
		public ISingleResult<ClecByMiles> CLEC_MILES([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,7)")] System.Nullable<decimal> lat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,7)")] System.Nullable<decimal> lon, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> milesRange, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string addressConcat)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lat, lon, milesRange, addressConcat);
			return ((ISingleResult<ClecByMiles>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="QUOTE_ORDER.GEO_QUOTE_LKP", IsComposable=true)]
		public IQueryable<GEO_QUOTE_LKPResult> GEO_QUOTE_LKP([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string lat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string lng, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> range)
		{
			return this.CreateMethodCallQuery<GEO_QUOTE_LKPResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lat, lng, range);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="COMET.GeoCoding_NNI", IsComposable=true)]
		public IQueryable<GeoCoding_NNIResult> GeoCoding_NNI([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,7)")] System.Nullable<decimal> lat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,7)")] System.Nullable<decimal> lon, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> range, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddressID", DbType="Int")] System.Nullable<int> addressID)
		{
			return this.CreateMethodCallQuery<GeoCoding_NNIResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lat, lon, range, addressID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="COMET.GeoCoding_EF", IsComposable=true)]
		public IQueryable<GeoCoding_EFResult> GeoCoding_EF([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,7)")] System.Nullable<decimal> lat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,7)")] System.Nullable<decimal> lon, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> milesRange, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ordering, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsHighSpeed", DbType="Bit")] System.Nullable<bool> isHighSpeed, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddressID", DbType="Int")] System.Nullable<int> addressID)
		{
			return this.CreateMethodCallQuery<GeoCoding_EFResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lat, lon, milesRange, ordering, isHighSpeed, addressID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="COMET.POINT_DETAILS_BOUNDARY", IsComposable=true)]
		public IQueryable<POINT_DETAILS_BOUNDARYResult> POINT_DETAILS_BOUNDARY([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LAT", DbType="VarChar(20)")] string lAT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LNG", DbType="VarChar(20)")] string lNG, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="POSTAL_CODE", DbType="VarChar(5)")] string pOSTAL_CODE)
		{
			return this.CreateMethodCallQuery<POINT_DETAILS_BOUNDARYResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lAT, lNG, pOSTAL_CODE);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="LOC.ADDRESSES_VW")]
	public partial class ADDRESSES_VW
	{
		
		private int _AddressId;
		
		private string _Zside_Premise;
		
		private string _Zside_Street;
		
		private string _Zside_City;
		
		private string _Zside_PostalCode;
		
		private string _Zside_State;
		
		private string _Zside_Country;
		
		private System.Nullable<decimal> _Zside_Latitude;
		
		private System.Nullable<decimal> _Zside_Longitude;
		
		private string _AddressCLLI;
		
		private string _SwcClli;
		
		public ADDRESSES_VW()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressId", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int AddressId
		{
			get
			{
				return this._AddressId;
			}
			set
			{
				if ((this._AddressId != value))
				{
					this._AddressId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_Premise", DbType="NVarChar(50)")]
		public string Zside_Premise
		{
			get
			{
				return this._Zside_Premise;
			}
			set
			{
				if ((this._Zside_Premise != value))
				{
					this._Zside_Premise = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_Street", DbType="NVarChar(255)")]
		public string Zside_Street
		{
			get
			{
				return this._Zside_Street;
			}
			set
			{
				if ((this._Zside_Street != value))
				{
					this._Zside_Street = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_City", DbType="NVarChar(100)")]
		public string Zside_City
		{
			get
			{
				return this._Zside_City;
			}
			set
			{
				if ((this._Zside_City != value))
				{
					this._Zside_City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_PostalCode", DbType="NVarChar(50)")]
		public string Zside_PostalCode
		{
			get
			{
				return this._Zside_PostalCode;
			}
			set
			{
				if ((this._Zside_PostalCode != value))
				{
					this._Zside_PostalCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_State", DbType="NVarChar(50)")]
		public string Zside_State
		{
			get
			{
				return this._Zside_State;
			}
			set
			{
				if ((this._Zside_State != value))
				{
					this._Zside_State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_Country", DbType="NVarChar(80)")]
		public string Zside_Country
		{
			get
			{
				return this._Zside_Country;
			}
			set
			{
				if ((this._Zside_Country != value))
				{
					this._Zside_Country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_Latitude", DbType="Decimal(15,6)")]
		public System.Nullable<decimal> Zside_Latitude
		{
			get
			{
				return this._Zside_Latitude;
			}
			set
			{
				if ((this._Zside_Latitude != value))
				{
					this._Zside_Latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_Longitude", DbType="Decimal(15,6)")]
		public System.Nullable<decimal> Zside_Longitude
		{
			get
			{
				return this._Zside_Longitude;
			}
			set
			{
				if ((this._Zside_Longitude != value))
				{
					this._Zside_Longitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressCLLI", DbType="NVarChar(8)")]
		public string AddressCLLI
		{
			get
			{
				return this._AddressCLLI;
			}
			set
			{
				if ((this._AddressCLLI != value))
				{
					this._AddressCLLI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SwcClli", DbType="NVarChar(8)")]
		public string SwcClli
		{
			get
			{
				return this._SwcClli;
			}
			set
			{
				if ((this._SwcClli != value))
				{
					this._SwcClli = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="COMET.ILEC_LOOKUP_VW")]
	public partial class ILEC_LOOKUP_VW
	{
		
		private int _LOC_NUM;
		
		private string _NODE_NAME;
		
		private string _LIFECYCLE_STATUS;
		
		private string _SITE_DISPOSITION;
		
		private string _FACILITY_TYPE;
		
		private string _RECORD_OWNER;
		
		private string _PRIMARY_HOMING_GATEWAY;
		
		private string _ILEC_CLLI;
		
		private string _AddressCLLI;
		
		private string _SWC_CLLI;
		
		private string _Zside_Premise;
		
		private string _Zside_Street;
		
		private string _Zside_City;
		
		private string _Zside_State;
		
		private string _Zside_PostalCode;
		
		private System.Nullable<decimal> _Zside_Latitude;
		
		private System.Nullable<decimal> _Zside_Longitude;
		
		public ILEC_LOOKUP_VW()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOC_NUM", DbType="Int NOT NULL")]
		public int LOC_NUM
		{
			get
			{
				return this._LOC_NUM;
			}
			set
			{
				if ((this._LOC_NUM != value))
				{
					this._LOC_NUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NODE_NAME", DbType="VarChar(150)")]
		public string NODE_NAME
		{
			get
			{
				return this._NODE_NAME;
			}
			set
			{
				if ((this._NODE_NAME != value))
				{
					this._NODE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIFECYCLE_STATUS", DbType="VarChar(20)")]
		public string LIFECYCLE_STATUS
		{
			get
			{
				return this._LIFECYCLE_STATUS;
			}
			set
			{
				if ((this._LIFECYCLE_STATUS != value))
				{
					this._LIFECYCLE_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITE_DISPOSITION", DbType="VarChar(20)")]
		public string SITE_DISPOSITION
		{
			get
			{
				return this._SITE_DISPOSITION;
			}
			set
			{
				if ((this._SITE_DISPOSITION != value))
				{
					this._SITE_DISPOSITION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FACILITY_TYPE", DbType="VarChar(20)")]
		public string FACILITY_TYPE
		{
			get
			{
				return this._FACILITY_TYPE;
			}
			set
			{
				if ((this._FACILITY_TYPE != value))
				{
					this._FACILITY_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECORD_OWNER", DbType="VarChar(20)")]
		public string RECORD_OWNER
		{
			get
			{
				return this._RECORD_OWNER;
			}
			set
			{
				if ((this._RECORD_OWNER != value))
				{
					this._RECORD_OWNER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMARY_HOMING_GATEWAY", DbType="VarChar(100)")]
		public string PRIMARY_HOMING_GATEWAY
		{
			get
			{
				return this._PRIMARY_HOMING_GATEWAY;
			}
			set
			{
				if ((this._PRIMARY_HOMING_GATEWAY != value))
				{
					this._PRIMARY_HOMING_GATEWAY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ILEC_CLLI", DbType="VarChar(8)")]
		public string ILEC_CLLI
		{
			get
			{
				return this._ILEC_CLLI;
			}
			set
			{
				if ((this._ILEC_CLLI != value))
				{
					this._ILEC_CLLI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressCLLI", DbType="NVarChar(8)")]
		public string AddressCLLI
		{
			get
			{
				return this._AddressCLLI;
			}
			set
			{
				if ((this._AddressCLLI != value))
				{
					this._AddressCLLI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SWC_CLLI", DbType="NVarChar(8)")]
		public string SWC_CLLI
		{
			get
			{
				return this._SWC_CLLI;
			}
			set
			{
				if ((this._SWC_CLLI != value))
				{
					this._SWC_CLLI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_Premise", DbType="NVarChar(50)")]
		public string Zside_Premise
		{
			get
			{
				return this._Zside_Premise;
			}
			set
			{
				if ((this._Zside_Premise != value))
				{
					this._Zside_Premise = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_Street", DbType="NVarChar(255)")]
		public string Zside_Street
		{
			get
			{
				return this._Zside_Street;
			}
			set
			{
				if ((this._Zside_Street != value))
				{
					this._Zside_Street = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_City", DbType="NVarChar(100)")]
		public string Zside_City
		{
			get
			{
				return this._Zside_City;
			}
			set
			{
				if ((this._Zside_City != value))
				{
					this._Zside_City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_State", DbType="NVarChar(50)")]
		public string Zside_State
		{
			get
			{
				return this._Zside_State;
			}
			set
			{
				if ((this._Zside_State != value))
				{
					this._Zside_State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_PostalCode", DbType="NVarChar(50)")]
		public string Zside_PostalCode
		{
			get
			{
				return this._Zside_PostalCode;
			}
			set
			{
				if ((this._Zside_PostalCode != value))
				{
					this._Zside_PostalCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_Latitude", DbType="Decimal(15,6)")]
		public System.Nullable<decimal> Zside_Latitude
		{
			get
			{
				return this._Zside_Latitude;
			}
			set
			{
				if ((this._Zside_Latitude != value))
				{
					this._Zside_Latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_Longitude", DbType="Decimal(15,6)")]
		public System.Nullable<decimal> Zside_Longitude
		{
			get
			{
				return this._Zside_Longitude;
			}
			set
			{
				if ((this._Zside_Longitude != value))
				{
					this._Zside_Longitude = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="COMET.EF_TRAIL")]
	public partial class EF_TRAIL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TRAIL_NAME;
		
		private System.Nullable<int> _RFAID;
		
		private string _VENDOR;
		
		private string _ECCKT;
		
		private int _HIGH_SPEED;
		
		private int _USED_SLOTS;
		
		private int _TOTAL_SLOTS;
		
		private System.Nullable<int> _AAddressID;
		
		private System.Nullable<int> _BAddressID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTRAIL_NAMEChanging(string value);
    partial void OnTRAIL_NAMEChanged();
    partial void OnRFAIDChanging(System.Nullable<int> value);
    partial void OnRFAIDChanged();
    partial void OnVENDORChanging(string value);
    partial void OnVENDORChanged();
    partial void OnECCKTChanging(string value);
    partial void OnECCKTChanged();
    partial void OnHIGH_SPEEDChanging(int value);
    partial void OnHIGH_SPEEDChanged();
    partial void OnUSED_SLOTSChanging(int value);
    partial void OnUSED_SLOTSChanged();
    partial void OnTOTAL_SLOTSChanging(int value);
    partial void OnTOTAL_SLOTSChanged();
    partial void OnAAddressIDChanging(System.Nullable<int> value);
    partial void OnAAddressIDChanged();
    partial void OnBAddressIDChanging(System.Nullable<int> value);
    partial void OnBAddressIDChanged();
    #endregion
		
		public EF_TRAIL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRAIL_NAME", DbType="VarChar(400) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TRAIL_NAME
		{
			get
			{
				return this._TRAIL_NAME;
			}
			set
			{
				if ((this._TRAIL_NAME != value))
				{
					this.OnTRAIL_NAMEChanging(value);
					this.SendPropertyChanging();
					this._TRAIL_NAME = value;
					this.SendPropertyChanged("TRAIL_NAME");
					this.OnTRAIL_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFAID", DbType="Int")]
		public System.Nullable<int> RFAID
		{
			get
			{
				return this._RFAID;
			}
			set
			{
				if ((this._RFAID != value))
				{
					this.OnRFAIDChanging(value);
					this.SendPropertyChanging();
					this._RFAID = value;
					this.SendPropertyChanged("RFAID");
					this.OnRFAIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VENDOR", DbType="NVarChar(100)")]
		public string VENDOR
		{
			get
			{
				return this._VENDOR;
			}
			set
			{
				if ((this._VENDOR != value))
				{
					this.OnVENDORChanging(value);
					this.SendPropertyChanging();
					this._VENDOR = value;
					this.SendPropertyChanged("VENDOR");
					this.OnVENDORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ECCKT", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
		public string ECCKT
		{
			get
			{
				return this._ECCKT;
			}
			set
			{
				if ((this._ECCKT != value))
				{
					this.OnECCKTChanging(value);
					this.SendPropertyChanging();
					this._ECCKT = value;
					this.SendPropertyChanged("ECCKT");
					this.OnECCKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIGH_SPEED", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int HIGH_SPEED
		{
			get
			{
				return this._HIGH_SPEED;
			}
			set
			{
				if ((this._HIGH_SPEED != value))
				{
					this.OnHIGH_SPEEDChanging(value);
					this.SendPropertyChanging();
					this._HIGH_SPEED = value;
					this.SendPropertyChanged("HIGH_SPEED");
					this.OnHIGH_SPEEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USED_SLOTS", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int USED_SLOTS
		{
			get
			{
				return this._USED_SLOTS;
			}
			set
			{
				if ((this._USED_SLOTS != value))
				{
					this.OnUSED_SLOTSChanging(value);
					this.SendPropertyChanging();
					this._USED_SLOTS = value;
					this.SendPropertyChanged("USED_SLOTS");
					this.OnUSED_SLOTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_SLOTS", DbType="Int NOT NULL")]
		public int TOTAL_SLOTS
		{
			get
			{
				return this._TOTAL_SLOTS;
			}
			set
			{
				if ((this._TOTAL_SLOTS != value))
				{
					this.OnTOTAL_SLOTSChanging(value);
					this.SendPropertyChanging();
					this._TOTAL_SLOTS = value;
					this.SendPropertyChanged("TOTAL_SLOTS");
					this.OnTOTAL_SLOTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AAddressID", DbType="Int")]
		public System.Nullable<int> AAddressID
		{
			get
			{
				return this._AAddressID;
			}
			set
			{
				if ((this._AAddressID != value))
				{
					this.OnAAddressIDChanging(value);
					this.SendPropertyChanging();
					this._AAddressID = value;
					this.SendPropertyChanged("AAddressID");
					this.OnAAddressIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAddressID", DbType="Int")]
		public System.Nullable<int> BAddressID
		{
			get
			{
				return this._BAddressID;
			}
			set
			{
				if ((this._BAddressID != value))
				{
					this.OnBAddressIDChanging(value);
					this.SendPropertyChanging();
					this._BAddressID = value;
					this.SendPropertyChanged("BAddressID");
					this.OnBAddressIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="COMET.SDP_ALL")]
	public partial class SDP_ALL
	{
		
		private int _Address_ID;
		
		private System.Nullable<decimal> _Zside_Latitude;
		
		private System.Nullable<decimal> _Zside_Longitude;
		
		private System.Nullable<int> _ATTRIBUTES;
		
		public SDP_ALL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_ID", DbType="Int NOT NULL")]
		public int Address_ID
		{
			get
			{
				return this._Address_ID;
			}
			set
			{
				if ((this._Address_ID != value))
				{
					this._Address_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_Latitude", DbType="Decimal(15,6)")]
		public System.Nullable<decimal> Zside_Latitude
		{
			get
			{
				return this._Zside_Latitude;
			}
			set
			{
				if ((this._Zside_Latitude != value))
				{
					this._Zside_Latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_Longitude", DbType="Decimal(15,6)")]
		public System.Nullable<decimal> Zside_Longitude
		{
			get
			{
				return this._Zside_Longitude;
			}
			set
			{
				if ((this._Zside_Longitude != value))
				{
					this._Zside_Longitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATTRIBUTES", DbType="Int")]
		public System.Nullable<int> ATTRIBUTES
		{
			get
			{
				return this._ATTRIBUTES;
			}
			set
			{
				if ((this._ATTRIBUTES != value))
				{
					this._ATTRIBUTES = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class SDP_TREND : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ADDRESS_ID;
		
		private System.Nullable<decimal> _HSEF1;
		
		private System.Nullable<decimal> _LSEF1;
		
		private System.Nullable<decimal> _NNI1;
		
		private System.Nullable<decimal> _HSEF2;
		
		private System.Nullable<decimal> _LSEF2;
		
		private System.Nullable<decimal> _NNI2;
		
		private System.Nullable<decimal> _HSEF3;
		
		private System.Nullable<decimal> _LSEF3;
		
		private System.Nullable<decimal> _NNI3;
		
		private System.Nullable<decimal> _HSEF4;
		
		private System.Nullable<decimal> _LSEF4;
		
		private System.Nullable<decimal> _NNI4;
		
		private System.Nullable<decimal> _HSEF5;
		
		private System.Nullable<decimal> _LSEF5;
		
		private System.Nullable<decimal> _NNI5;
		
		private System.Nullable<decimal> _HSEF6;
		
		private System.Nullable<decimal> _LSEF6;
		
		private System.Nullable<decimal> _NNI6;
		
		private System.Nullable<decimal> _HSEF7;
		
		private System.Nullable<decimal> _LSEF7;
		
		private System.Nullable<decimal> _NNI7;
		
		private System.Nullable<decimal> _HSEF8;
		
		private System.Nullable<decimal> _LSEF8;
		
		private System.Nullable<decimal> _NNI8;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnADDRESS_IDChanging(int value);
    partial void OnADDRESS_IDChanged();
    partial void OnHSEF1Changing(System.Nullable<decimal> value);
    partial void OnHSEF1Changed();
    partial void OnLSEF1Changing(System.Nullable<decimal> value);
    partial void OnLSEF1Changed();
    partial void OnNNI1Changing(System.Nullable<decimal> value);
    partial void OnNNI1Changed();
    partial void OnHSEF2Changing(System.Nullable<decimal> value);
    partial void OnHSEF2Changed();
    partial void OnLSEF2Changing(System.Nullable<decimal> value);
    partial void OnLSEF2Changed();
    partial void OnNNI2Changing(System.Nullable<decimal> value);
    partial void OnNNI2Changed();
    partial void OnHSEF3Changing(System.Nullable<decimal> value);
    partial void OnHSEF3Changed();
    partial void OnLSEF3Changing(System.Nullable<decimal> value);
    partial void OnLSEF3Changed();
    partial void OnNNI3Changing(System.Nullable<decimal> value);
    partial void OnNNI3Changed();
    partial void OnHSEF4Changing(System.Nullable<decimal> value);
    partial void OnHSEF4Changed();
    partial void OnLSEF4Changing(System.Nullable<decimal> value);
    partial void OnLSEF4Changed();
    partial void OnNNI4Changing(System.Nullable<decimal> value);
    partial void OnNNI4Changed();
    partial void OnHSEF5Changing(System.Nullable<decimal> value);
    partial void OnHSEF5Changed();
    partial void OnLSEF5Changing(System.Nullable<decimal> value);
    partial void OnLSEF5Changed();
    partial void OnNNI5Changing(System.Nullable<decimal> value);
    partial void OnNNI5Changed();
    partial void OnHSEF6Changing(System.Nullable<decimal> value);
    partial void OnHSEF6Changed();
    partial void OnLSEF6Changing(System.Nullable<decimal> value);
    partial void OnLSEF6Changed();
    partial void OnNNI6Changing(System.Nullable<decimal> value);
    partial void OnNNI6Changed();
    partial void OnHSEF7Changing(System.Nullable<decimal> value);
    partial void OnHSEF7Changed();
    partial void OnLSEF7Changing(System.Nullable<decimal> value);
    partial void OnLSEF7Changed();
    partial void OnNNI7Changing(System.Nullable<decimal> value);
    partial void OnNNI7Changed();
    partial void OnHSEF8Changing(System.Nullable<decimal> value);
    partial void OnHSEF8Changed();
    partial void OnLSEF8Changing(System.Nullable<decimal> value);
    partial void OnLSEF8Changed();
    partial void OnNNI8Changing(System.Nullable<decimal> value);
    partial void OnNNI8Changed();
    #endregion
		
		public SDP_TREND()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS_ID", IsPrimaryKey=true)]
		public int ADDRESS_ID
		{
			get
			{
				return this._ADDRESS_ID;
			}
			set
			{
				if ((this._ADDRESS_ID != value))
				{
					this.OnADDRESS_IDChanging(value);
					this.SendPropertyChanging();
					this._ADDRESS_ID = value;
					this.SendPropertyChanged("ADDRESS_ID");
					this.OnADDRESS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSEF1")]
		public System.Nullable<decimal> HSEF1
		{
			get
			{
				return this._HSEF1;
			}
			set
			{
				if ((this._HSEF1 != value))
				{
					this.OnHSEF1Changing(value);
					this.SendPropertyChanging();
					this._HSEF1 = value;
					this.SendPropertyChanged("HSEF1");
					this.OnHSEF1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSEF1")]
		public System.Nullable<decimal> LSEF1
		{
			get
			{
				return this._LSEF1;
			}
			set
			{
				if ((this._LSEF1 != value))
				{
					this.OnLSEF1Changing(value);
					this.SendPropertyChanging();
					this._LSEF1 = value;
					this.SendPropertyChanged("LSEF1");
					this.OnLSEF1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI1")]
		public System.Nullable<decimal> NNI1
		{
			get
			{
				return this._NNI1;
			}
			set
			{
				if ((this._NNI1 != value))
				{
					this.OnNNI1Changing(value);
					this.SendPropertyChanging();
					this._NNI1 = value;
					this.SendPropertyChanged("NNI1");
					this.OnNNI1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSEF2")]
		public System.Nullable<decimal> HSEF2
		{
			get
			{
				return this._HSEF2;
			}
			set
			{
				if ((this._HSEF2 != value))
				{
					this.OnHSEF2Changing(value);
					this.SendPropertyChanging();
					this._HSEF2 = value;
					this.SendPropertyChanged("HSEF2");
					this.OnHSEF2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSEF2")]
		public System.Nullable<decimal> LSEF2
		{
			get
			{
				return this._LSEF2;
			}
			set
			{
				if ((this._LSEF2 != value))
				{
					this.OnLSEF2Changing(value);
					this.SendPropertyChanging();
					this._LSEF2 = value;
					this.SendPropertyChanged("LSEF2");
					this.OnLSEF2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI2")]
		public System.Nullable<decimal> NNI2
		{
			get
			{
				return this._NNI2;
			}
			set
			{
				if ((this._NNI2 != value))
				{
					this.OnNNI2Changing(value);
					this.SendPropertyChanging();
					this._NNI2 = value;
					this.SendPropertyChanged("NNI2");
					this.OnNNI2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSEF3")]
		public System.Nullable<decimal> HSEF3
		{
			get
			{
				return this._HSEF3;
			}
			set
			{
				if ((this._HSEF3 != value))
				{
					this.OnHSEF3Changing(value);
					this.SendPropertyChanging();
					this._HSEF3 = value;
					this.SendPropertyChanged("HSEF3");
					this.OnHSEF3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSEF3")]
		public System.Nullable<decimal> LSEF3
		{
			get
			{
				return this._LSEF3;
			}
			set
			{
				if ((this._LSEF3 != value))
				{
					this.OnLSEF3Changing(value);
					this.SendPropertyChanging();
					this._LSEF3 = value;
					this.SendPropertyChanged("LSEF3");
					this.OnLSEF3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI3")]
		public System.Nullable<decimal> NNI3
		{
			get
			{
				return this._NNI3;
			}
			set
			{
				if ((this._NNI3 != value))
				{
					this.OnNNI3Changing(value);
					this.SendPropertyChanging();
					this._NNI3 = value;
					this.SendPropertyChanged("NNI3");
					this.OnNNI3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSEF4")]
		public System.Nullable<decimal> HSEF4
		{
			get
			{
				return this._HSEF4;
			}
			set
			{
				if ((this._HSEF4 != value))
				{
					this.OnHSEF4Changing(value);
					this.SendPropertyChanging();
					this._HSEF4 = value;
					this.SendPropertyChanged("HSEF4");
					this.OnHSEF4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSEF4")]
		public System.Nullable<decimal> LSEF4
		{
			get
			{
				return this._LSEF4;
			}
			set
			{
				if ((this._LSEF4 != value))
				{
					this.OnLSEF4Changing(value);
					this.SendPropertyChanging();
					this._LSEF4 = value;
					this.SendPropertyChanged("LSEF4");
					this.OnLSEF4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI4")]
		public System.Nullable<decimal> NNI4
		{
			get
			{
				return this._NNI4;
			}
			set
			{
				if ((this._NNI4 != value))
				{
					this.OnNNI4Changing(value);
					this.SendPropertyChanging();
					this._NNI4 = value;
					this.SendPropertyChanged("NNI4");
					this.OnNNI4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSEF5")]
		public System.Nullable<decimal> HSEF5
		{
			get
			{
				return this._HSEF5;
			}
			set
			{
				if ((this._HSEF5 != value))
				{
					this.OnHSEF5Changing(value);
					this.SendPropertyChanging();
					this._HSEF5 = value;
					this.SendPropertyChanged("HSEF5");
					this.OnHSEF5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSEF5")]
		public System.Nullable<decimal> LSEF5
		{
			get
			{
				return this._LSEF5;
			}
			set
			{
				if ((this._LSEF5 != value))
				{
					this.OnLSEF5Changing(value);
					this.SendPropertyChanging();
					this._LSEF5 = value;
					this.SendPropertyChanged("LSEF5");
					this.OnLSEF5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI5")]
		public System.Nullable<decimal> NNI5
		{
			get
			{
				return this._NNI5;
			}
			set
			{
				if ((this._NNI5 != value))
				{
					this.OnNNI5Changing(value);
					this.SendPropertyChanging();
					this._NNI5 = value;
					this.SendPropertyChanged("NNI5");
					this.OnNNI5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSEF6")]
		public System.Nullable<decimal> HSEF6
		{
			get
			{
				return this._HSEF6;
			}
			set
			{
				if ((this._HSEF6 != value))
				{
					this.OnHSEF6Changing(value);
					this.SendPropertyChanging();
					this._HSEF6 = value;
					this.SendPropertyChanged("HSEF6");
					this.OnHSEF6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSEF6")]
		public System.Nullable<decimal> LSEF6
		{
			get
			{
				return this._LSEF6;
			}
			set
			{
				if ((this._LSEF6 != value))
				{
					this.OnLSEF6Changing(value);
					this.SendPropertyChanging();
					this._LSEF6 = value;
					this.SendPropertyChanged("LSEF6");
					this.OnLSEF6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI6")]
		public System.Nullable<decimal> NNI6
		{
			get
			{
				return this._NNI6;
			}
			set
			{
				if ((this._NNI6 != value))
				{
					this.OnNNI6Changing(value);
					this.SendPropertyChanging();
					this._NNI6 = value;
					this.SendPropertyChanged("NNI6");
					this.OnNNI6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSEF7")]
		public System.Nullable<decimal> HSEF7
		{
			get
			{
				return this._HSEF7;
			}
			set
			{
				if ((this._HSEF7 != value))
				{
					this.OnHSEF7Changing(value);
					this.SendPropertyChanging();
					this._HSEF7 = value;
					this.SendPropertyChanged("HSEF7");
					this.OnHSEF7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSEF7")]
		public System.Nullable<decimal> LSEF7
		{
			get
			{
				return this._LSEF7;
			}
			set
			{
				if ((this._LSEF7 != value))
				{
					this.OnLSEF7Changing(value);
					this.SendPropertyChanging();
					this._LSEF7 = value;
					this.SendPropertyChanged("LSEF7");
					this.OnLSEF7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI7")]
		public System.Nullable<decimal> NNI7
		{
			get
			{
				return this._NNI7;
			}
			set
			{
				if ((this._NNI7 != value))
				{
					this.OnNNI7Changing(value);
					this.SendPropertyChanging();
					this._NNI7 = value;
					this.SendPropertyChanged("NNI7");
					this.OnNNI7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSEF8")]
		public System.Nullable<decimal> HSEF8
		{
			get
			{
				return this._HSEF8;
			}
			set
			{
				if ((this._HSEF8 != value))
				{
					this.OnHSEF8Changing(value);
					this.SendPropertyChanging();
					this._HSEF8 = value;
					this.SendPropertyChanged("HSEF8");
					this.OnHSEF8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSEF8")]
		public System.Nullable<decimal> LSEF8
		{
			get
			{
				return this._LSEF8;
			}
			set
			{
				if ((this._LSEF8 != value))
				{
					this.OnLSEF8Changing(value);
					this.SendPropertyChanging();
					this._LSEF8 = value;
					this.SendPropertyChanged("LSEF8");
					this.OnLSEF8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI8")]
		public System.Nullable<decimal> NNI8
		{
			get
			{
				return this._NNI8;
			}
			set
			{
				if ((this._NNI8 != value))
				{
					this.OnNNI8Changing(value);
					this.SendPropertyChanging();
					this._NNI8 = value;
					this.SendPropertyChanged("NNI8");
					this.OnNNI8Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class ClecByMiles
	{
		
		private string _XREF_PARENT_VENDOR;
		
		private string _VENDOR_TYPE;
		
		private string _CLLI_CD;
		
		private string _ADDRESS_1;
		
		private string _CITY;
		
		private string _STATE_CD;
		
		private string _ZIPCODE;
		
		private string _COUNTRY;
		
		private decimal _Latitude;
		
		private decimal _Longitude;
		
		private long _RANK;
		
		private decimal _Miles;
		
		public ClecByMiles()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XREF_PARENT_VENDOR", CanBeNull=false)]
		public string XREF_PARENT_VENDOR
		{
			get
			{
				return this._XREF_PARENT_VENDOR;
			}
			set
			{
				if ((this._XREF_PARENT_VENDOR != value))
				{
					this._XREF_PARENT_VENDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VENDOR_TYPE", CanBeNull=false)]
		public string VENDOR_TYPE
		{
			get
			{
				return this._VENDOR_TYPE;
			}
			set
			{
				if ((this._VENDOR_TYPE != value))
				{
					this._VENDOR_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLLI_CD", CanBeNull=false)]
		public string CLLI_CD
		{
			get
			{
				return this._CLLI_CD;
			}
			set
			{
				if ((this._CLLI_CD != value))
				{
					this._CLLI_CD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS_1", CanBeNull=false)]
		public string ADDRESS_1
		{
			get
			{
				return this._ADDRESS_1;
			}
			set
			{
				if ((this._ADDRESS_1 != value))
				{
					this._ADDRESS_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", CanBeNull=false)]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this._CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_CD", CanBeNull=false)]
		public string STATE_CD
		{
			get
			{
				return this._STATE_CD;
			}
			set
			{
				if ((this._STATE_CD != value))
				{
					this._STATE_CD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZIPCODE", CanBeNull=false)]
		public string ZIPCODE
		{
			get
			{
				return this._ZIPCODE;
			}
			set
			{
				if ((this._ZIPCODE != value))
				{
					this._ZIPCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRY", CanBeNull=false)]
		public string COUNTRY
		{
			get
			{
				return this._COUNTRY;
			}
			set
			{
				if ((this._COUNTRY != value))
				{
					this._COUNTRY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude")]
		public decimal Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this._Latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude")]
		public decimal Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this._Longitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RANK")]
		public long RANK
		{
			get
			{
				return this._RANK;
			}
			set
			{
				if ((this._RANK != value))
				{
					this._RANK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Miles")]
		public decimal Miles
		{
			get
			{
				return this._Miles;
			}
			set
			{
				if ((this._Miles != value))
				{
					this._Miles = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="CAP.T_NNI_FAC")]
	public partial class T_NNI_FAC
	{
		
		private string _NNI_ZEND_TRAIL_STATE_CD;
		
		private string _NNI_ZEND_TRAIL_CITY;
		
		private string _NNI_ZEND_TRAIL_CLLI_CD;
		
		private string _NNI_ZEND_TRAIL_ADDRESS;
		
		private string _NNI_ZEND_TRAIL_LATA;
		
		private string _NNI_ZEND_REGION;
		
		private string _NNI_TRAIL_NAME;
		
		private string _NNI_TRAIL_TYPE;
		
		private System.Nullable<System.DateTime> _TRAIL_CREATED_DATE;
		
		private string _TRAIL_STATUS_CD;
		
		private string _TRAIL_ORDER_NUMBER;
		
		private System.Nullable<int> _RFA_ID;
		
		private string _RFA_CREATED_BY;
		
		private System.Nullable<System.DateTime> _RFA_CREATE_DT;
		
		private System.Nullable<System.DateTime> _RFA_DESIRED_DUE_DT;
		
		private string _RFA_STATUS;
		
		private string _RFA_PROJECT_NAME;
		
		private string _RFA_VENDOR_PRODUCT;
		
		private string _RFA_NOTES;
		
		private string _TRAIL_GROUP_NAME;
		
		private string _NNIFAC_USED_FOR_TYPE;
		
		private string _TRAIL_BANDWIDTH_CD;
		
		private System.Nullable<int> _NNI_FAC_RATE;
		
		private string _NNI_FAC_ECCKT_VENDOR;
		
		private string _NNI_FAC_ECCKT_ULT_VENDOR;
		
		private string _NNI_VENDOR_TYPE;
		
		private string _NNI_FAC_ECCKT;
		
		private string _NNI_FAC_ECCKT_LTID_NAME;
		
		private string _NETWORK_ELEMENT_NAME;
		
		private string _EQUIPMENT_DEFINITION;
		
		private string _MGT_NE_NAME;
		
		private string _PORT_NAME;
		
		private int _ECCKT_COUNT;
		
		private decimal _ECCKT_MRC;
		
		private string _PNUM;
		
		private decimal _ECCKT_OCC_AMT;
		
		private System.Nullable<decimal> _TOTAL_ECCKT_MRC;
		
		private System.Nullable<decimal> _RFA_TOTAL_MRC;
		
		private System.Nullable<decimal> _ACT_VS_RFA_EXP_MRC;
		
		private System.Nullable<int> _AVAIL_MBPS;
		
		private System.Nullable<int> _USED_MBPS;
		
		private System.Nullable<int> _TOTAL_MBPS;
		
		private System.Nullable<double> _UTILIZATION;
		
		private string _NNI_SOURCE;
		
		private System.Nullable<System.DateTime> _NNI_TRAIL_IN_SERVICE_DATE;
		
		private string _CONSOLIDATION_OPP_IND;
		
		public T_NNI_FAC()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI_ZEND_TRAIL_STATE_CD", DbType="VarChar(35)")]
		public string NNI_ZEND_TRAIL_STATE_CD
		{
			get
			{
				return this._NNI_ZEND_TRAIL_STATE_CD;
			}
			set
			{
				if ((this._NNI_ZEND_TRAIL_STATE_CD != value))
				{
					this._NNI_ZEND_TRAIL_STATE_CD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI_ZEND_TRAIL_CITY", DbType="VarChar(60)")]
		public string NNI_ZEND_TRAIL_CITY
		{
			get
			{
				return this._NNI_ZEND_TRAIL_CITY;
			}
			set
			{
				if ((this._NNI_ZEND_TRAIL_CITY != value))
				{
					this._NNI_ZEND_TRAIL_CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI_ZEND_TRAIL_CLLI_CD", DbType="VarChar(44)")]
		public string NNI_ZEND_TRAIL_CLLI_CD
		{
			get
			{
				return this._NNI_ZEND_TRAIL_CLLI_CD;
			}
			set
			{
				if ((this._NNI_ZEND_TRAIL_CLLI_CD != value))
				{
					this._NNI_ZEND_TRAIL_CLLI_CD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI_ZEND_TRAIL_ADDRESS", DbType="VarChar(60)")]
		public string NNI_ZEND_TRAIL_ADDRESS
		{
			get
			{
				return this._NNI_ZEND_TRAIL_ADDRESS;
			}
			set
			{
				if ((this._NNI_ZEND_TRAIL_ADDRESS != value))
				{
					this._NNI_ZEND_TRAIL_ADDRESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI_ZEND_TRAIL_LATA", DbType="VarChar(3)")]
		public string NNI_ZEND_TRAIL_LATA
		{
			get
			{
				return this._NNI_ZEND_TRAIL_LATA;
			}
			set
			{
				if ((this._NNI_ZEND_TRAIL_LATA != value))
				{
					this._NNI_ZEND_TRAIL_LATA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI_ZEND_REGION", DbType="NVarChar(30)")]
		public string NNI_ZEND_REGION
		{
			get
			{
				return this._NNI_ZEND_REGION;
			}
			set
			{
				if ((this._NNI_ZEND_REGION != value))
				{
					this._NNI_ZEND_REGION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI_TRAIL_NAME", DbType="VarChar(400)")]
		public string NNI_TRAIL_NAME
		{
			get
			{
				return this._NNI_TRAIL_NAME;
			}
			set
			{
				if ((this._NNI_TRAIL_NAME != value))
				{
					this._NNI_TRAIL_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI_TRAIL_TYPE", DbType="VarChar(50)")]
		public string NNI_TRAIL_TYPE
		{
			get
			{
				return this._NNI_TRAIL_TYPE;
			}
			set
			{
				if ((this._NNI_TRAIL_TYPE != value))
				{
					this._NNI_TRAIL_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRAIL_CREATED_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> TRAIL_CREATED_DATE
		{
			get
			{
				return this._TRAIL_CREATED_DATE;
			}
			set
			{
				if ((this._TRAIL_CREATED_DATE != value))
				{
					this._TRAIL_CREATED_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRAIL_STATUS_CD", DbType="VarChar(120)")]
		public string TRAIL_STATUS_CD
		{
			get
			{
				return this._TRAIL_STATUS_CD;
			}
			set
			{
				if ((this._TRAIL_STATUS_CD != value))
				{
					this._TRAIL_STATUS_CD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRAIL_ORDER_NUMBER", DbType="VarChar(50)")]
		public string TRAIL_ORDER_NUMBER
		{
			get
			{
				return this._TRAIL_ORDER_NUMBER;
			}
			set
			{
				if ((this._TRAIL_ORDER_NUMBER != value))
				{
					this._TRAIL_ORDER_NUMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFA_ID", DbType="Int")]
		public System.Nullable<int> RFA_ID
		{
			get
			{
				return this._RFA_ID;
			}
			set
			{
				if ((this._RFA_ID != value))
				{
					this._RFA_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFA_CREATED_BY", DbType="NVarChar(50)")]
		public string RFA_CREATED_BY
		{
			get
			{
				return this._RFA_CREATED_BY;
			}
			set
			{
				if ((this._RFA_CREATED_BY != value))
				{
					this._RFA_CREATED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFA_CREATE_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> RFA_CREATE_DT
		{
			get
			{
				return this._RFA_CREATE_DT;
			}
			set
			{
				if ((this._RFA_CREATE_DT != value))
				{
					this._RFA_CREATE_DT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFA_DESIRED_DUE_DT", DbType="Date")]
		public System.Nullable<System.DateTime> RFA_DESIRED_DUE_DT
		{
			get
			{
				return this._RFA_DESIRED_DUE_DT;
			}
			set
			{
				if ((this._RFA_DESIRED_DUE_DT != value))
				{
					this._RFA_DESIRED_DUE_DT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFA_STATUS", DbType="NVarChar(50)")]
		public string RFA_STATUS
		{
			get
			{
				return this._RFA_STATUS;
			}
			set
			{
				if ((this._RFA_STATUS != value))
				{
					this._RFA_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFA_PROJECT_NAME", DbType="NVarChar(100)")]
		public string RFA_PROJECT_NAME
		{
			get
			{
				return this._RFA_PROJECT_NAME;
			}
			set
			{
				if ((this._RFA_PROJECT_NAME != value))
				{
					this._RFA_PROJECT_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFA_VENDOR_PRODUCT", DbType="VarChar(50)")]
		public string RFA_VENDOR_PRODUCT
		{
			get
			{
				return this._RFA_VENDOR_PRODUCT;
			}
			set
			{
				if ((this._RFA_VENDOR_PRODUCT != value))
				{
					this._RFA_VENDOR_PRODUCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFA_NOTES", DbType="NVarChar(2000)")]
		public string RFA_NOTES
		{
			get
			{
				return this._RFA_NOTES;
			}
			set
			{
				if ((this._RFA_NOTES != value))
				{
					this._RFA_NOTES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRAIL_GROUP_NAME", DbType="VarChar(200)")]
		public string TRAIL_GROUP_NAME
		{
			get
			{
				return this._TRAIL_GROUP_NAME;
			}
			set
			{
				if ((this._TRAIL_GROUP_NAME != value))
				{
					this._TRAIL_GROUP_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNIFAC_USED_FOR_TYPE", DbType="VarChar(120)")]
		public string NNIFAC_USED_FOR_TYPE
		{
			get
			{
				return this._NNIFAC_USED_FOR_TYPE;
			}
			set
			{
				if ((this._NNIFAC_USED_FOR_TYPE != value))
				{
					this._NNIFAC_USED_FOR_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRAIL_BANDWIDTH_CD", DbType="VarChar(120)")]
		public string TRAIL_BANDWIDTH_CD
		{
			get
			{
				return this._TRAIL_BANDWIDTH_CD;
			}
			set
			{
				if ((this._TRAIL_BANDWIDTH_CD != value))
				{
					this._TRAIL_BANDWIDTH_CD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI_FAC_RATE", DbType="Int")]
		public System.Nullable<int> NNI_FAC_RATE
		{
			get
			{
				return this._NNI_FAC_RATE;
			}
			set
			{
				if ((this._NNI_FAC_RATE != value))
				{
					this._NNI_FAC_RATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI_FAC_ECCKT_VENDOR", DbType="NVarChar(200)")]
		public string NNI_FAC_ECCKT_VENDOR
		{
			get
			{
				return this._NNI_FAC_ECCKT_VENDOR;
			}
			set
			{
				if ((this._NNI_FAC_ECCKT_VENDOR != value))
				{
					this._NNI_FAC_ECCKT_VENDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI_FAC_ECCKT_ULT_VENDOR", DbType="NVarChar(200)")]
		public string NNI_FAC_ECCKT_ULT_VENDOR
		{
			get
			{
				return this._NNI_FAC_ECCKT_ULT_VENDOR;
			}
			set
			{
				if ((this._NNI_FAC_ECCKT_ULT_VENDOR != value))
				{
					this._NNI_FAC_ECCKT_ULT_VENDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI_VENDOR_TYPE", DbType="NVarChar(50)")]
		public string NNI_VENDOR_TYPE
		{
			get
			{
				return this._NNI_VENDOR_TYPE;
			}
			set
			{
				if ((this._NNI_VENDOR_TYPE != value))
				{
					this._NNI_VENDOR_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI_FAC_ECCKT", DbType="VarChar(255)")]
		public string NNI_FAC_ECCKT
		{
			get
			{
				return this._NNI_FAC_ECCKT;
			}
			set
			{
				if ((this._NNI_FAC_ECCKT != value))
				{
					this._NNI_FAC_ECCKT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI_FAC_ECCKT_LTID_NAME", DbType="VarChar(400)")]
		public string NNI_FAC_ECCKT_LTID_NAME
		{
			get
			{
				return this._NNI_FAC_ECCKT_LTID_NAME;
			}
			set
			{
				if ((this._NNI_FAC_ECCKT_LTID_NAME != value))
				{
					this._NNI_FAC_ECCKT_LTID_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NETWORK_ELEMENT_NAME", DbType="VarChar(300)")]
		public string NETWORK_ELEMENT_NAME
		{
			get
			{
				return this._NETWORK_ELEMENT_NAME;
			}
			set
			{
				if ((this._NETWORK_ELEMENT_NAME != value))
				{
					this._NETWORK_ELEMENT_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQUIPMENT_DEFINITION", DbType="VarChar(120)")]
		public string EQUIPMENT_DEFINITION
		{
			get
			{
				return this._EQUIPMENT_DEFINITION;
			}
			set
			{
				if ((this._EQUIPMENT_DEFINITION != value))
				{
					this._EQUIPMENT_DEFINITION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MGT_NE_NAME", DbType="VarChar(300)")]
		public string MGT_NE_NAME
		{
			get
			{
				return this._MGT_NE_NAME;
			}
			set
			{
				if ((this._MGT_NE_NAME != value))
				{
					this._MGT_NE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PORT_NAME", DbType="VarChar(1024)")]
		public string PORT_NAME
		{
			get
			{
				return this._PORT_NAME;
			}
			set
			{
				if ((this._PORT_NAME != value))
				{
					this._PORT_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ECCKT_COUNT", DbType="Int NOT NULL")]
		public int ECCKT_COUNT
		{
			get
			{
				return this._ECCKT_COUNT;
			}
			set
			{
				if ((this._ECCKT_COUNT != value))
				{
					this._ECCKT_COUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ECCKT_MRC", DbType="Money NOT NULL")]
		public decimal ECCKT_MRC
		{
			get
			{
				return this._ECCKT_MRC;
			}
			set
			{
				if ((this._ECCKT_MRC != value))
				{
					this._ECCKT_MRC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNUM", DbType="VarChar(80)")]
		public string PNUM
		{
			get
			{
				return this._PNUM;
			}
			set
			{
				if ((this._PNUM != value))
				{
					this._PNUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ECCKT_OCC_AMT", DbType="Money NOT NULL")]
		public decimal ECCKT_OCC_AMT
		{
			get
			{
				return this._ECCKT_OCC_AMT;
			}
			set
			{
				if ((this._ECCKT_OCC_AMT != value))
				{
					this._ECCKT_OCC_AMT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_ECCKT_MRC", DbType="Money")]
		public System.Nullable<decimal> TOTAL_ECCKT_MRC
		{
			get
			{
				return this._TOTAL_ECCKT_MRC;
			}
			set
			{
				if ((this._TOTAL_ECCKT_MRC != value))
				{
					this._TOTAL_ECCKT_MRC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFA_TOTAL_MRC", DbType="Money")]
		public System.Nullable<decimal> RFA_TOTAL_MRC
		{
			get
			{
				return this._RFA_TOTAL_MRC;
			}
			set
			{
				if ((this._RFA_TOTAL_MRC != value))
				{
					this._RFA_TOTAL_MRC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACT_VS_RFA_EXP_MRC", DbType="Money")]
		public System.Nullable<decimal> ACT_VS_RFA_EXP_MRC
		{
			get
			{
				return this._ACT_VS_RFA_EXP_MRC;
			}
			set
			{
				if ((this._ACT_VS_RFA_EXP_MRC != value))
				{
					this._ACT_VS_RFA_EXP_MRC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVAIL_MBPS", DbType="Int")]
		public System.Nullable<int> AVAIL_MBPS
		{
			get
			{
				return this._AVAIL_MBPS;
			}
			set
			{
				if ((this._AVAIL_MBPS != value))
				{
					this._AVAIL_MBPS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USED_MBPS", DbType="Int")]
		public System.Nullable<int> USED_MBPS
		{
			get
			{
				return this._USED_MBPS;
			}
			set
			{
				if ((this._USED_MBPS != value))
				{
					this._USED_MBPS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_MBPS", DbType="Int")]
		public System.Nullable<int> TOTAL_MBPS
		{
			get
			{
				return this._TOTAL_MBPS;
			}
			set
			{
				if ((this._TOTAL_MBPS != value))
				{
					this._TOTAL_MBPS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UTILIZATION", DbType="Float")]
		public System.Nullable<double> UTILIZATION
		{
			get
			{
				return this._UTILIZATION;
			}
			set
			{
				if ((this._UTILIZATION != value))
				{
					this._UTILIZATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI_SOURCE", DbType="VarChar(20)")]
		public string NNI_SOURCE
		{
			get
			{
				return this._NNI_SOURCE;
			}
			set
			{
				if ((this._NNI_SOURCE != value))
				{
					this._NNI_SOURCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI_TRAIL_IN_SERVICE_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> NNI_TRAIL_IN_SERVICE_DATE
		{
			get
			{
				return this._NNI_TRAIL_IN_SERVICE_DATE;
			}
			set
			{
				if ((this._NNI_TRAIL_IN_SERVICE_DATE != value))
				{
					this._NNI_TRAIL_IN_SERVICE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONSOLIDATION_OPP_IND", DbType="VarChar(1)")]
		public string CONSOLIDATION_OPP_IND
		{
			get
			{
				return this._CONSOLIDATION_OPP_IND;
			}
			set
			{
				if ((this._CONSOLIDATION_OPP_IND != value))
				{
					this._CONSOLIDATION_OPP_IND = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="COMET.LOCATION_ASSET")]
	public partial class LOCATION_ASSET
	{
		
		private string _Zside_Premise;
		
		private string _Zside_Street;
		
		private string _Zside_City;
		
		private string _Zside_State;
		
		private string _AddressCLLI;
		
		private System.Nullable<decimal> _Zside_Latitude;
		
		private System.Nullable<decimal> _Zside_Longitude;
		
		private System.Nullable<int> _ADDRESS_ID;
		
		private System.Nullable<int> _LATA;
		
		private System.Nullable<int> _SDP_TRAIL_NUM;
		
		private System.Nullable<int> _NUM_OF_TRAIL_LSEF;
		
		private System.Nullable<int> _NUM_OF_TRAIL_HSEF;
		
		private System.Nullable<int> _NUM_OF_NNI;
		
		private System.Nullable<decimal> _UTILIZATION_LSEF;
		
		private System.Nullable<decimal> _UTILIZATION_HSEF;
		
		private System.Nullable<decimal> _UTILIZATION_NNI;
		
		private System.Nullable<decimal> _CUST_IND_PERC;
		
		private System.Nullable<decimal> _CUST_HYBRID_IND_PERC;
		
		private System.Nullable<decimal> _SWITCH_IND_PERC;
		
		private System.Nullable<decimal> _IP_NET_IND_PERC;
		
		private System.Nullable<decimal> _NET_OTHER_IND_PERC;
		
		private System.Nullable<decimal> _NO_PROD_IND_PERC;
		
		private string _NODE_NAME;
		
		private string _LIFECYCLE_STATUS;
		
		private string _SITE_DISPOSITION;
		
		private string _FACILITY_TYPE;
		
		private string _RECORD_OWNER;
		
		private string _PRIMARY_HOMING_GATEWAY;
		
		private string _ILEC_CLLI;
		
		private System.Nullable<decimal> _LSEF_TREND_SLOPE;
		
		private System.Nullable<decimal> _HSEF_TREND_SLOPE;
		
		private System.Nullable<decimal> _NNI_TREND_SLOPE;
		
		public LOCATION_ASSET()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_Premise", DbType="NVarChar(50)")]
		public string Zside_Premise
		{
			get
			{
				return this._Zside_Premise;
			}
			set
			{
				if ((this._Zside_Premise != value))
				{
					this._Zside_Premise = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_Street", DbType="NVarChar(255)")]
		public string Zside_Street
		{
			get
			{
				return this._Zside_Street;
			}
			set
			{
				if ((this._Zside_Street != value))
				{
					this._Zside_Street = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_City", DbType="NVarChar(100)")]
		public string Zside_City
		{
			get
			{
				return this._Zside_City;
			}
			set
			{
				if ((this._Zside_City != value))
				{
					this._Zside_City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_State", DbType="NVarChar(50)")]
		public string Zside_State
		{
			get
			{
				return this._Zside_State;
			}
			set
			{
				if ((this._Zside_State != value))
				{
					this._Zside_State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressCLLI", DbType="NVarChar(8)")]
		public string AddressCLLI
		{
			get
			{
				return this._AddressCLLI;
			}
			set
			{
				if ((this._AddressCLLI != value))
				{
					this._AddressCLLI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_Latitude", DbType="Decimal(15,6)")]
		public System.Nullable<decimal> Zside_Latitude
		{
			get
			{
				return this._Zside_Latitude;
			}
			set
			{
				if ((this._Zside_Latitude != value))
				{
					this._Zside_Latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_Longitude", DbType="Decimal(15,6)")]
		public System.Nullable<decimal> Zside_Longitude
		{
			get
			{
				return this._Zside_Longitude;
			}
			set
			{
				if ((this._Zside_Longitude != value))
				{
					this._Zside_Longitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS_ID", DbType="Int")]
		public System.Nullable<int> ADDRESS_ID
		{
			get
			{
				return this._ADDRESS_ID;
			}
			set
			{
				if ((this._ADDRESS_ID != value))
				{
					this._ADDRESS_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATA", DbType="Int")]
		public System.Nullable<int> LATA
		{
			get
			{
				return this._LATA;
			}
			set
			{
				if ((this._LATA != value))
				{
					this._LATA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDP_TRAIL_NUM", DbType="Int")]
		public System.Nullable<int> SDP_TRAIL_NUM
		{
			get
			{
				return this._SDP_TRAIL_NUM;
			}
			set
			{
				if ((this._SDP_TRAIL_NUM != value))
				{
					this._SDP_TRAIL_NUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUM_OF_TRAIL_LSEF", DbType="Int")]
		public System.Nullable<int> NUM_OF_TRAIL_LSEF
		{
			get
			{
				return this._NUM_OF_TRAIL_LSEF;
			}
			set
			{
				if ((this._NUM_OF_TRAIL_LSEF != value))
				{
					this._NUM_OF_TRAIL_LSEF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUM_OF_TRAIL_HSEF", DbType="Int")]
		public System.Nullable<int> NUM_OF_TRAIL_HSEF
		{
			get
			{
				return this._NUM_OF_TRAIL_HSEF;
			}
			set
			{
				if ((this._NUM_OF_TRAIL_HSEF != value))
				{
					this._NUM_OF_TRAIL_HSEF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUM_OF_NNI", DbType="Int")]
		public System.Nullable<int> NUM_OF_NNI
		{
			get
			{
				return this._NUM_OF_NNI;
			}
			set
			{
				if ((this._NUM_OF_NNI != value))
				{
					this._NUM_OF_NNI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UTILIZATION_LSEF", DbType="Decimal(5,1)")]
		public System.Nullable<decimal> UTILIZATION_LSEF
		{
			get
			{
				return this._UTILIZATION_LSEF;
			}
			set
			{
				if ((this._UTILIZATION_LSEF != value))
				{
					this._UTILIZATION_LSEF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UTILIZATION_HSEF", DbType="Decimal(5,1)")]
		public System.Nullable<decimal> UTILIZATION_HSEF
		{
			get
			{
				return this._UTILIZATION_HSEF;
			}
			set
			{
				if ((this._UTILIZATION_HSEF != value))
				{
					this._UTILIZATION_HSEF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UTILIZATION_NNI", DbType="Decimal(5,1)")]
		public System.Nullable<decimal> UTILIZATION_NNI
		{
			get
			{
				return this._UTILIZATION_NNI;
			}
			set
			{
				if ((this._UTILIZATION_NNI != value))
				{
					this._UTILIZATION_NNI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_IND_PERC", DbType="Decimal(5,1)")]
		public System.Nullable<decimal> CUST_IND_PERC
		{
			get
			{
				return this._CUST_IND_PERC;
			}
			set
			{
				if ((this._CUST_IND_PERC != value))
				{
					this._CUST_IND_PERC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_HYBRID_IND_PERC", DbType="Decimal(5,1)")]
		public System.Nullable<decimal> CUST_HYBRID_IND_PERC
		{
			get
			{
				return this._CUST_HYBRID_IND_PERC;
			}
			set
			{
				if ((this._CUST_HYBRID_IND_PERC != value))
				{
					this._CUST_HYBRID_IND_PERC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SWITCH_IND_PERC", DbType="Decimal(5,1)")]
		public System.Nullable<decimal> SWITCH_IND_PERC
		{
			get
			{
				return this._SWITCH_IND_PERC;
			}
			set
			{
				if ((this._SWITCH_IND_PERC != value))
				{
					this._SWITCH_IND_PERC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP_NET_IND_PERC", DbType="Decimal(5,1)")]
		public System.Nullable<decimal> IP_NET_IND_PERC
		{
			get
			{
				return this._IP_NET_IND_PERC;
			}
			set
			{
				if ((this._IP_NET_IND_PERC != value))
				{
					this._IP_NET_IND_PERC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NET_OTHER_IND_PERC", DbType="Decimal(5,1)")]
		public System.Nullable<decimal> NET_OTHER_IND_PERC
		{
			get
			{
				return this._NET_OTHER_IND_PERC;
			}
			set
			{
				if ((this._NET_OTHER_IND_PERC != value))
				{
					this._NET_OTHER_IND_PERC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO_PROD_IND_PERC", DbType="Decimal(5,1)")]
		public System.Nullable<decimal> NO_PROD_IND_PERC
		{
			get
			{
				return this._NO_PROD_IND_PERC;
			}
			set
			{
				if ((this._NO_PROD_IND_PERC != value))
				{
					this._NO_PROD_IND_PERC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NODE_NAME", DbType="VarChar(150)")]
		public string NODE_NAME
		{
			get
			{
				return this._NODE_NAME;
			}
			set
			{
				if ((this._NODE_NAME != value))
				{
					this._NODE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIFECYCLE_STATUS", DbType="VarChar(20)")]
		public string LIFECYCLE_STATUS
		{
			get
			{
				return this._LIFECYCLE_STATUS;
			}
			set
			{
				if ((this._LIFECYCLE_STATUS != value))
				{
					this._LIFECYCLE_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SITE_DISPOSITION", DbType="VarChar(20)")]
		public string SITE_DISPOSITION
		{
			get
			{
				return this._SITE_DISPOSITION;
			}
			set
			{
				if ((this._SITE_DISPOSITION != value))
				{
					this._SITE_DISPOSITION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FACILITY_TYPE", DbType="VarChar(20)")]
		public string FACILITY_TYPE
		{
			get
			{
				return this._FACILITY_TYPE;
			}
			set
			{
				if ((this._FACILITY_TYPE != value))
				{
					this._FACILITY_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECORD_OWNER", DbType="VarChar(30)")]
		public string RECORD_OWNER
		{
			get
			{
				return this._RECORD_OWNER;
			}
			set
			{
				if ((this._RECORD_OWNER != value))
				{
					this._RECORD_OWNER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMARY_HOMING_GATEWAY", DbType="VarChar(100)")]
		public string PRIMARY_HOMING_GATEWAY
		{
			get
			{
				return this._PRIMARY_HOMING_GATEWAY;
			}
			set
			{
				if ((this._PRIMARY_HOMING_GATEWAY != value))
				{
					this._PRIMARY_HOMING_GATEWAY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ILEC_CLLI", DbType="VarChar(8)")]
		public string ILEC_CLLI
		{
			get
			{
				return this._ILEC_CLLI;
			}
			set
			{
				if ((this._ILEC_CLLI != value))
				{
					this._ILEC_CLLI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LSEF_TREND_SLOPE", DbType="Decimal(7,5)")]
		public System.Nullable<decimal> LSEF_TREND_SLOPE
		{
			get
			{
				return this._LSEF_TREND_SLOPE;
			}
			set
			{
				if ((this._LSEF_TREND_SLOPE != value))
				{
					this._LSEF_TREND_SLOPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSEF_TREND_SLOPE", DbType="Decimal(5,3)")]
		public System.Nullable<decimal> HSEF_TREND_SLOPE
		{
			get
			{
				return this._HSEF_TREND_SLOPE;
			}
			set
			{
				if ((this._HSEF_TREND_SLOPE != value))
				{
					this._HSEF_TREND_SLOPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI_TREND_SLOPE", DbType="Decimal(7,5)")]
		public System.Nullable<decimal> NNI_TREND_SLOPE
		{
			get
			{
				return this._NNI_TREND_SLOPE;
			}
			set
			{
				if ((this._NNI_TREND_SLOPE != value))
				{
					this._NNI_TREND_SLOPE = value;
				}
			}
		}
	}
	
	public partial class GEO_QUOTE_LKPResult
	{
		
		private int _Address_ID;
		
		private int _EntityLineItemId;
		
		private string _BandwidthDesc;
		
		private string _ProductDesc;
		
		private System.Nullable<decimal> _mrcUSD;
		
		private string _Vendor;
		
		private string _Vendor_Type;
		
		private System.Nullable<int> _PriceTermId;
		
		private System.Nullable<decimal> _IncrementalMrCost;
		
		private System.Nullable<decimal> _IncrementalNrCost;
		
		private System.Nullable<bool> _IsWin;
		
		private System.Nullable<double> _BandwidthEthernet;
		
		private System.Nullable<double> _BandwidthCapacity;
		
		private System.Nullable<System.DateTime> _QuoteCreateDate;
		
		private string _Zside_Premise;
		
		private string _Zside_street;
		
		private string _Zside_City;
		
		private string _Zside_State;
		
		private string _CLLI_CD;
		
		private string _SWC_CLLI;
		
		private System.Nullable<double> _Distance;
		
		private System.Nullable<decimal> _Zside_Latitude;
		
		private System.Nullable<decimal> _Zside_Longitude;
		
		private System.Nullable<long> _RANK;
		
		public GEO_QUOTE_LKPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_ID", DbType="Int NOT NULL")]
		public int Address_ID
		{
			get
			{
				return this._Address_ID;
			}
			set
			{
				if ((this._Address_ID != value))
				{
					this._Address_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntityLineItemId", DbType="Int NOT NULL")]
		public int EntityLineItemId
		{
			get
			{
				return this._EntityLineItemId;
			}
			set
			{
				if ((this._EntityLineItemId != value))
				{
					this._EntityLineItemId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BandwidthDesc", DbType="NVarChar(50)")]
		public string BandwidthDesc
		{
			get
			{
				return this._BandwidthDesc;
			}
			set
			{
				if ((this._BandwidthDesc != value))
				{
					this._BandwidthDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductDesc", DbType="NVarChar(512)")]
		public string ProductDesc
		{
			get
			{
				return this._ProductDesc;
			}
			set
			{
				if ((this._ProductDesc != value))
				{
					this._ProductDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mrcUSD", DbType="Money")]
		public System.Nullable<decimal> mrcUSD
		{
			get
			{
				return this._mrcUSD;
			}
			set
			{
				if ((this._mrcUSD != value))
				{
					this._mrcUSD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vendor", DbType="NVarChar(300)")]
		public string Vendor
		{
			get
			{
				return this._Vendor;
			}
			set
			{
				if ((this._Vendor != value))
				{
					this._Vendor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vendor_Type", DbType="NVarChar(90)")]
		public string Vendor_Type
		{
			get
			{
				return this._Vendor_Type;
			}
			set
			{
				if ((this._Vendor_Type != value))
				{
					this._Vendor_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceTermId", DbType="Int")]
		public System.Nullable<int> PriceTermId
		{
			get
			{
				return this._PriceTermId;
			}
			set
			{
				if ((this._PriceTermId != value))
				{
					this._PriceTermId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IncrementalMrCost", DbType="Money")]
		public System.Nullable<decimal> IncrementalMrCost
		{
			get
			{
				return this._IncrementalMrCost;
			}
			set
			{
				if ((this._IncrementalMrCost != value))
				{
					this._IncrementalMrCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IncrementalNrCost", DbType="Money")]
		public System.Nullable<decimal> IncrementalNrCost
		{
			get
			{
				return this._IncrementalNrCost;
			}
			set
			{
				if ((this._IncrementalNrCost != value))
				{
					this._IncrementalNrCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsWin", DbType="Bit")]
		public System.Nullable<bool> IsWin
		{
			get
			{
				return this._IsWin;
			}
			set
			{
				if ((this._IsWin != value))
				{
					this._IsWin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BandwidthEthernet", DbType="Float")]
		public System.Nullable<double> BandwidthEthernet
		{
			get
			{
				return this._BandwidthEthernet;
			}
			set
			{
				if ((this._BandwidthEthernet != value))
				{
					this._BandwidthEthernet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BandwidthCapacity", DbType="Float")]
		public System.Nullable<double> BandwidthCapacity
		{
			get
			{
				return this._BandwidthCapacity;
			}
			set
			{
				if ((this._BandwidthCapacity != value))
				{
					this._BandwidthCapacity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuoteCreateDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> QuoteCreateDate
		{
			get
			{
				return this._QuoteCreateDate;
			}
			set
			{
				if ((this._QuoteCreateDate != value))
				{
					this._QuoteCreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_Premise", DbType="NVarChar(50)")]
		public string Zside_Premise
		{
			get
			{
				return this._Zside_Premise;
			}
			set
			{
				if ((this._Zside_Premise != value))
				{
					this._Zside_Premise = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_street", DbType="NVarChar(255)")]
		public string Zside_street
		{
			get
			{
				return this._Zside_street;
			}
			set
			{
				if ((this._Zside_street != value))
				{
					this._Zside_street = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_City", DbType="NVarChar(100)")]
		public string Zside_City
		{
			get
			{
				return this._Zside_City;
			}
			set
			{
				if ((this._Zside_City != value))
				{
					this._Zside_City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_State", DbType="NVarChar(50)")]
		public string Zside_State
		{
			get
			{
				return this._Zside_State;
			}
			set
			{
				if ((this._Zside_State != value))
				{
					this._Zside_State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLLI_CD", DbType="NVarChar(8)")]
		public string CLLI_CD
		{
			get
			{
				return this._CLLI_CD;
			}
			set
			{
				if ((this._CLLI_CD != value))
				{
					this._CLLI_CD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SWC_CLLI", DbType="NVarChar(8)")]
		public string SWC_CLLI
		{
			get
			{
				return this._SWC_CLLI;
			}
			set
			{
				if ((this._SWC_CLLI != value))
				{
					this._SWC_CLLI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distance", DbType="Float")]
		public System.Nullable<double> Distance
		{
			get
			{
				return this._Distance;
			}
			set
			{
				if ((this._Distance != value))
				{
					this._Distance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_Latitude", DbType="Decimal(15,6)")]
		public System.Nullable<decimal> Zside_Latitude
		{
			get
			{
				return this._Zside_Latitude;
			}
			set
			{
				if ((this._Zside_Latitude != value))
				{
					this._Zside_Latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_Longitude", DbType="Decimal(15,6)")]
		public System.Nullable<decimal> Zside_Longitude
		{
			get
			{
				return this._Zside_Longitude;
			}
			set
			{
				if ((this._Zside_Longitude != value))
				{
					this._Zside_Longitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RANK", DbType="BigInt")]
		public System.Nullable<long> RANK
		{
			get
			{
				return this._RANK;
			}
			set
			{
				if ((this._RANK != value))
				{
					this._RANK = value;
				}
			}
		}
	}
	
	public partial class GeoCoding_NNIResult
	{
		
		private string _NNI_TRAIL_NAME;
		
		private System.Nullable<int> _RFA_ID;
		
		private string _NNI_FAC_ECCKT_VENDOR;
		
		private string _NNI_FAC_ECCKT;
		
		private System.Nullable<int> _USED_MBPS;
		
		private System.Nullable<int> _TOTAL_MBPS;
		
		private int _Address_ID;
		
		private string _Zside_Premise;
		
		private string _Zside_Street;
		
		private string _Zside_City;
		
		private string _Zside_State;
		
		private string _Zside_PostalCode;
		
		private System.Nullable<decimal> _Zside_Latitude;
		
		private System.Nullable<decimal> _Zside_Longitude;
		
		private System.Nullable<long> _RANK;
		
		public GeoCoding_NNIResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI_TRAIL_NAME", DbType="VarChar(400)")]
		public string NNI_TRAIL_NAME
		{
			get
			{
				return this._NNI_TRAIL_NAME;
			}
			set
			{
				if ((this._NNI_TRAIL_NAME != value))
				{
					this._NNI_TRAIL_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFA_ID", DbType="Int")]
		public System.Nullable<int> RFA_ID
		{
			get
			{
				return this._RFA_ID;
			}
			set
			{
				if ((this._RFA_ID != value))
				{
					this._RFA_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI_FAC_ECCKT_VENDOR", DbType="NVarChar(200)")]
		public string NNI_FAC_ECCKT_VENDOR
		{
			get
			{
				return this._NNI_FAC_ECCKT_VENDOR;
			}
			set
			{
				if ((this._NNI_FAC_ECCKT_VENDOR != value))
				{
					this._NNI_FAC_ECCKT_VENDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NNI_FAC_ECCKT", DbType="VarChar(255)")]
		public string NNI_FAC_ECCKT
		{
			get
			{
				return this._NNI_FAC_ECCKT;
			}
			set
			{
				if ((this._NNI_FAC_ECCKT != value))
				{
					this._NNI_FAC_ECCKT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USED_MBPS", DbType="Int")]
		public System.Nullable<int> USED_MBPS
		{
			get
			{
				return this._USED_MBPS;
			}
			set
			{
				if ((this._USED_MBPS != value))
				{
					this._USED_MBPS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_MBPS", DbType="Int")]
		public System.Nullable<int> TOTAL_MBPS
		{
			get
			{
				return this._TOTAL_MBPS;
			}
			set
			{
				if ((this._TOTAL_MBPS != value))
				{
					this._TOTAL_MBPS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_ID", DbType="Int NOT NULL")]
		public int Address_ID
		{
			get
			{
				return this._Address_ID;
			}
			set
			{
				if ((this._Address_ID != value))
				{
					this._Address_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_Premise", DbType="NVarChar(50)")]
		public string Zside_Premise
		{
			get
			{
				return this._Zside_Premise;
			}
			set
			{
				if ((this._Zside_Premise != value))
				{
					this._Zside_Premise = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_Street", DbType="NVarChar(255)")]
		public string Zside_Street
		{
			get
			{
				return this._Zside_Street;
			}
			set
			{
				if ((this._Zside_Street != value))
				{
					this._Zside_Street = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_City", DbType="NVarChar(100)")]
		public string Zside_City
		{
			get
			{
				return this._Zside_City;
			}
			set
			{
				if ((this._Zside_City != value))
				{
					this._Zside_City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_State", DbType="NVarChar(50)")]
		public string Zside_State
		{
			get
			{
				return this._Zside_State;
			}
			set
			{
				if ((this._Zside_State != value))
				{
					this._Zside_State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_PostalCode", DbType="NVarChar(50)")]
		public string Zside_PostalCode
		{
			get
			{
				return this._Zside_PostalCode;
			}
			set
			{
				if ((this._Zside_PostalCode != value))
				{
					this._Zside_PostalCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_Latitude", DbType="Decimal(15,6)")]
		public System.Nullable<decimal> Zside_Latitude
		{
			get
			{
				return this._Zside_Latitude;
			}
			set
			{
				if ((this._Zside_Latitude != value))
				{
					this._Zside_Latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zside_Longitude", DbType="Decimal(15,6)")]
		public System.Nullable<decimal> Zside_Longitude
		{
			get
			{
				return this._Zside_Longitude;
			}
			set
			{
				if ((this._Zside_Longitude != value))
				{
					this._Zside_Longitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RANK", DbType="BigInt")]
		public System.Nullable<long> RANK
		{
			get
			{
				return this._RANK;
			}
			set
			{
				if ((this._RANK != value))
				{
					this._RANK = value;
				}
			}
		}
	}
	
	public partial class GeoCoding_EFResult
	{
		
		private string _LEGACY;
		
		private string _Trail_Name;
		
		private System.Nullable<int> _RFAID;
		
		private string _VENDOR;
		
		private string _ECCKT;
		
		private int _HIGH_SPEED;
		
		private int _USED_SLOTS;
		
		private int _TOTAL_SLOTS;
		
		private int _Address_ID;
		
		private string _Premise;
		
		private string _Street;
		
		private string _City;
		
		private string _PostalCode;
		
		private string _StateCd;
		
		private System.Nullable<decimal> _Latitude;
		
		private System.Nullable<decimal> _Longitude;
		
		private System.Nullable<long> _Ranking;
		
		public GeoCoding_EFResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEGACY", DbType="VarChar(50)")]
		public string LEGACY
		{
			get
			{
				return this._LEGACY;
			}
			set
			{
				if ((this._LEGACY != value))
				{
					this._LEGACY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trail_Name", DbType="VarChar(400) NOT NULL", CanBeNull=false)]
		public string Trail_Name
		{
			get
			{
				return this._Trail_Name;
			}
			set
			{
				if ((this._Trail_Name != value))
				{
					this._Trail_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFAID", DbType="Int")]
		public System.Nullable<int> RFAID
		{
			get
			{
				return this._RFAID;
			}
			set
			{
				if ((this._RFAID != value))
				{
					this._RFAID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VENDOR", DbType="NVarChar(100)")]
		public string VENDOR
		{
			get
			{
				return this._VENDOR;
			}
			set
			{
				if ((this._VENDOR != value))
				{
					this._VENDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ECCKT", DbType="NVarChar(2000)")]
		public string ECCKT
		{
			get
			{
				return this._ECCKT;
			}
			set
			{
				if ((this._ECCKT != value))
				{
					this._ECCKT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIGH_SPEED", DbType="Int NOT NULL")]
		public int HIGH_SPEED
		{
			get
			{
				return this._HIGH_SPEED;
			}
			set
			{
				if ((this._HIGH_SPEED != value))
				{
					this._HIGH_SPEED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USED_SLOTS", DbType="Int NOT NULL")]
		public int USED_SLOTS
		{
			get
			{
				return this._USED_SLOTS;
			}
			set
			{
				if ((this._USED_SLOTS != value))
				{
					this._USED_SLOTS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_SLOTS", DbType="Int NOT NULL")]
		public int TOTAL_SLOTS
		{
			get
			{
				return this._TOTAL_SLOTS;
			}
			set
			{
				if ((this._TOTAL_SLOTS != value))
				{
					this._TOTAL_SLOTS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_ID", DbType="Int NOT NULL")]
		public int Address_ID
		{
			get
			{
				return this._Address_ID;
			}
			set
			{
				if ((this._Address_ID != value))
				{
					this._Address_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Premise", DbType="NVarChar(50)")]
		public string Premise
		{
			get
			{
				return this._Premise;
			}
			set
			{
				if ((this._Premise != value))
				{
					this._Premise = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street", DbType="NVarChar(255)")]
		public string Street
		{
			get
			{
				return this._Street;
			}
			set
			{
				if ((this._Street != value))
				{
					this._Street = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(100)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalCode", DbType="NVarChar(50)")]
		public string PostalCode
		{
			get
			{
				return this._PostalCode;
			}
			set
			{
				if ((this._PostalCode != value))
				{
					this._PostalCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateCd", DbType="NVarChar(50)")]
		public string StateCd
		{
			get
			{
				return this._StateCd;
			}
			set
			{
				if ((this._StateCd != value))
				{
					this._StateCd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Decimal(15,6)")]
		public System.Nullable<decimal> Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this._Latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Decimal(15,6)")]
		public System.Nullable<decimal> Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this._Longitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ranking", DbType="BigInt")]
		public System.Nullable<long> Ranking
		{
			get
			{
				return this._Ranking;
			}
			set
			{
				if ((this._Ranking != value))
				{
					this._Ranking = value;
				}
			}
		}
	}
	
	public partial class POINT_DETAILS_BOUNDARYResult
	{
		
		private System.Nullable<short> _LATA;
		
		private string _SWC;
		
		private string _LEC_VENDOR;
		
		private string _MSO;
		
		private string _POSTAL_CODE;
		
		public POINT_DETAILS_BOUNDARYResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATA", DbType="SmallInt")]
		public System.Nullable<short> LATA
		{
			get
			{
				return this._LATA;
			}
			set
			{
				if ((this._LATA != value))
				{
					this._LATA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SWC", DbType="VarChar(8)")]
		public string SWC
		{
			get
			{
				return this._SWC;
			}
			set
			{
				if ((this._SWC != value))
				{
					this._SWC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEC_VENDOR", DbType="VarChar(250)")]
		public string LEC_VENDOR
		{
			get
			{
				return this._LEC_VENDOR;
			}
			set
			{
				if ((this._LEC_VENDOR != value))
				{
					this._LEC_VENDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSO", DbType="NVarChar(255)")]
		public string MSO
		{
			get
			{
				return this._MSO;
			}
			set
			{
				if ((this._MSO != value))
				{
					this._MSO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTAL_CODE", DbType="NVarChar(5)")]
		public string POSTAL_CODE
		{
			get
			{
				return this._POSTAL_CODE;
			}
			set
			{
				if ((this._POSTAL_CODE != value))
				{
					this._POSTAL_CODE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
