#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMET.Server.Domain
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GAM_Complex_Op")]
	public partial class ReferenceDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLKP_VENDOR_LOCKED(LKP_VENDOR_LOCKED instance);
    partial void UpdateLKP_VENDOR_LOCKED(LKP_VENDOR_LOCKED instance);
    partial void DeleteLKP_VENDOR_LOCKED(LKP_VENDOR_LOCKED instance);
    #endregion
		
		public ReferenceDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReferenceDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReferenceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReferenceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LKP_POSTAL_CD_STATE> LKP_POSTAL_CD_STATEs
		{
			get
			{
				return this.GetTable<LKP_POSTAL_CD_STATE>();
			}
		}
		
		public System.Data.Linq.Table<CABLE_OPERATOR_AREAS_FCC_EXCEL> CABLE_OPERATOR_AREAS_FCC_EXCELs
		{
			get
			{
				return this.GetTable<CABLE_OPERATOR_AREAS_FCC_EXCEL>();
			}
		}
		
		public System.Data.Linq.Table<LKP_VENDOR_TYP_XREF_EXCEL> LKP_VENDOR_TYP_XREF_EXCELs
		{
			get
			{
				return this.GetTable<LKP_VENDOR_TYP_XREF_EXCEL>();
			}
		}
		
		public System.Data.Linq.Table<ReferenceTableUpdate> ReferenceTableUpdates
		{
			get
			{
				return this.GetTable<ReferenceTableUpdate>();
			}
		}
		
		public System.Data.Linq.Table<STATES_ABBREVIATION> STATES_ABBREVIATIONs
		{
			get
			{
				return this.GetTable<STATES_ABBREVIATION>();
			}
		}
		
		public System.Data.Linq.Table<LKP_VENDOR_LOCKED> LKP_VENDOR_LOCKEDs
		{
			get
			{
				return this.GetTable<LKP_VENDOR_LOCKED>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="LOC.LKP_POSTAL_CD_STATE")]
	public partial class LKP_POSTAL_CD_STATE
	{
		
		private string _POSTAL_CODE;
		
		private string _STATE_CD;
		
		public LKP_POSTAL_CD_STATE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTAL_CODE", DbType="VarChar(5)")]
		public string POSTAL_CODE
		{
			get
			{
				return this._POSTAL_CODE;
			}
			set
			{
				if ((this._POSTAL_CODE != value))
				{
					this._POSTAL_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_CD", DbType="VarChar(35)")]
		public string STATE_CD
		{
			get
			{
				return this._STATE_CD;
			}
			set
			{
				if ((this._STATE_CD != value))
				{
					this._STATE_CD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="VENDOR.CABLE_OPERATOR_AREAS_FCC_EXCEL")]
	public partial class CABLE_OPERATOR_AREAS_FCC_EXCEL
	{
		
		private string _Community_Unit;
		
		private string _Community_Name;
		
		private string _Municipality_Type;
		
		private string _County_Name;
		
		private string _Legal_Name;
		
		private string _Assumed_Name;
		
		private string _CUID_Status;
		
		private System.Nullable<double> _status;
		
		private string _Merged_CUID;
		
		private string _PSID;
		
		private System.Nullable<System.DateTime> _Date_Operational;
		
		private string _Address;
		
		private string _PO_Box;
		
		private string _City;
		
		private string _State;
		
		private string _Zip_Code;
		
		private string _CITY_DERIVED;
		
		private string _STATE_DERIVED;
		
		private string _CITY_STATE_DERIVED;
		
		public CABLE_OPERATOR_AREAS_FCC_EXCEL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Community Unit]", Storage="_Community_Unit", DbType="NVarChar(255)")]
		public string Community_Unit
		{
			get
			{
				return this._Community_Unit;
			}
			set
			{
				if ((this._Community_Unit != value))
				{
					this._Community_Unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Community Name]", Storage="_Community_Name", DbType="NVarChar(255)")]
		public string Community_Name
		{
			get
			{
				return this._Community_Name;
			}
			set
			{
				if ((this._Community_Name != value))
				{
					this._Community_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Municipality Type]", Storage="_Municipality_Type", DbType="NVarChar(255)")]
		public string Municipality_Type
		{
			get
			{
				return this._Municipality_Type;
			}
			set
			{
				if ((this._Municipality_Type != value))
				{
					this._Municipality_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[County Name]", Storage="_County_Name", DbType="NVarChar(255)")]
		public string County_Name
		{
			get
			{
				return this._County_Name;
			}
			set
			{
				if ((this._County_Name != value))
				{
					this._County_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Legal Name]", Storage="_Legal_Name", DbType="NVarChar(255)")]
		public string Legal_Name
		{
			get
			{
				return this._Legal_Name;
			}
			set
			{
				if ((this._Legal_Name != value))
				{
					this._Legal_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Assumed Name]", Storage="_Assumed_Name", DbType="NVarChar(255)")]
		public string Assumed_Name
		{
			get
			{
				return this._Assumed_Name;
			}
			set
			{
				if ((this._Assumed_Name != value))
				{
					this._Assumed_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CUID Status]", Storage="_CUID_Status", DbType="NVarChar(255)")]
		public string CUID_Status
		{
			get
			{
				return this._CUID_Status;
			}
			set
			{
				if ((this._CUID_Status != value))
				{
					this._CUID_Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Float")]
		public System.Nullable<double> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Merged CUID]", Storage="_Merged_CUID", DbType="NVarChar(255)")]
		public string Merged_CUID
		{
			get
			{
				return this._Merged_CUID;
			}
			set
			{
				if ((this._Merged_CUID != value))
				{
					this._Merged_CUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PSID", DbType="NVarChar(255)")]
		public string PSID
		{
			get
			{
				return this._PSID;
			}
			set
			{
				if ((this._PSID != value))
				{
					this._PSID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Date Operational]", Storage="_Date_Operational", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date_Operational
		{
			get
			{
				return this._Date_Operational;
			}
			set
			{
				if ((this._Date_Operational != value))
				{
					this._Date_Operational = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(255)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PO Box]", Storage="_PO_Box", DbType="NVarChar(255)")]
		public string PO_Box
		{
			get
			{
				return this._PO_Box;
			}
			set
			{
				if ((this._PO_Box != value))
				{
					this._PO_Box = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(255)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(255)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Zip Code]", Storage="_Zip_Code", DbType="NVarChar(255)")]
		public string Zip_Code
		{
			get
			{
				return this._Zip_Code;
			}
			set
			{
				if ((this._Zip_Code != value))
				{
					this._Zip_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY_DERIVED", DbType="NVarChar(255)")]
		public string CITY_DERIVED
		{
			get
			{
				return this._CITY_DERIVED;
			}
			set
			{
				if ((this._CITY_DERIVED != value))
				{
					this._CITY_DERIVED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_DERIVED", DbType="NVarChar(255)")]
		public string STATE_DERIVED
		{
			get
			{
				return this._STATE_DERIVED;
			}
			set
			{
				if ((this._STATE_DERIVED != value))
				{
					this._STATE_DERIVED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY_STATE_DERIVED", DbType="NVarChar(255)")]
		public string CITY_STATE_DERIVED
		{
			get
			{
				return this._CITY_STATE_DERIVED;
			}
			set
			{
				if ((this._CITY_STATE_DERIVED != value))
				{
					this._CITY_STATE_DERIVED = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="VENDOR.LKP_VENDOR_TYP_XREF_EXCEL")]
	public partial class LKP_VENDOR_TYP_XREF_EXCEL
	{
		
		private string _UPPER_VENDOR_NAME;
		
		private string _VENDOR_TYPE;
		
		private string _VENDOR_NORM_NAME;
		
		private string _XREF_PARENT_VENDOR;
		
		private string _SOURCE;
		
		public LKP_VENDOR_TYP_XREF_EXCEL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPPER_VENDOR_NAME", DbType="NVarChar(255)")]
		public string UPPER_VENDOR_NAME
		{
			get
			{
				return this._UPPER_VENDOR_NAME;
			}
			set
			{
				if ((this._UPPER_VENDOR_NAME != value))
				{
					this._UPPER_VENDOR_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VENDOR_TYPE", DbType="NVarChar(255)")]
		public string VENDOR_TYPE
		{
			get
			{
				return this._VENDOR_TYPE;
			}
			set
			{
				if ((this._VENDOR_TYPE != value))
				{
					this._VENDOR_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VENDOR_NORM_NAME", DbType="NVarChar(255)")]
		public string VENDOR_NORM_NAME
		{
			get
			{
				return this._VENDOR_NORM_NAME;
			}
			set
			{
				if ((this._VENDOR_NORM_NAME != value))
				{
					this._VENDOR_NORM_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XREF_PARENT_VENDOR", DbType="NVarChar(255)")]
		public string XREF_PARENT_VENDOR
		{
			get
			{
				return this._XREF_PARENT_VENDOR;
			}
			set
			{
				if ((this._XREF_PARENT_VENDOR != value))
				{
					this._XREF_PARENT_VENDOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOURCE", DbType="NVarChar(255)")]
		public string SOURCE
		{
			get
			{
				return this._SOURCE;
			}
			set
			{
				if ((this._SOURCE != value))
				{
					this._SOURCE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="COMET.ReferenceTableUpdates")]
	public partial class ReferenceTableUpdate
	{
		
		private System.Nullable<System.DateTime> _SDP_UPDATED;
		
		private System.Nullable<System.DateTime> _VENDOR_XREF_UPDATED;
		
		public ReferenceTableUpdate()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDP_UPDATED", DbType="DateTime")]
		public System.Nullable<System.DateTime> SDP_UPDATED
		{
			get
			{
				return this._SDP_UPDATED;
			}
			set
			{
				if ((this._SDP_UPDATED != value))
				{
					this._SDP_UPDATED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VENDOR_XREF_UPDATED", DbType="DateTime")]
		public System.Nullable<System.DateTime> VENDOR_XREF_UPDATED
		{
			get
			{
				return this._VENDOR_XREF_UPDATED;
			}
			set
			{
				if ((this._VENDOR_XREF_UPDATED != value))
				{
					this._VENDOR_XREF_UPDATED = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="LOC.STATES_ABBREVIATION")]
	public partial class STATES_ABBREVIATION
	{
		
		private System.Nullable<int> _id;
		
		private string _name;
		
		private string _abbreviation;
		
		private string _country;
		
		private string _type;
		
		private System.Nullable<int> _sort;
		
		private string _status;
		
		private string _occupied;
		
		private string _notes;
		
		private string _fips_state;
		
		private string _assoc_press;
		
		private string _standard_federal_region;
		
		private string _census_region;
		
		private string _census_region_name;
		
		private string _census_division;
		
		private string _census_division_name;
		
		private string _circuit_court;
		
		public STATES_ABBREVIATION()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(255)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abbreviation", DbType="VarChar(255)")]
		public string abbreviation
		{
			get
			{
				return this._abbreviation;
			}
			set
			{
				if ((this._abbreviation != value))
				{
					this._abbreviation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="VarChar(255)")]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this._country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(255)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sort", DbType="Int")]
		public System.Nullable<int> sort
		{
			get
			{
				return this._sort;
			}
			set
			{
				if ((this._sort != value))
				{
					this._sort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(255)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_occupied", DbType="VarChar(255)")]
		public string occupied
		{
			get
			{
				return this._occupied;
			}
			set
			{
				if ((this._occupied != value))
				{
					this._occupied = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notes", DbType="VarChar(255)")]
		public string notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				if ((this._notes != value))
				{
					this._notes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fips_state", DbType="VarChar(255)")]
		public string fips_state
		{
			get
			{
				return this._fips_state;
			}
			set
			{
				if ((this._fips_state != value))
				{
					this._fips_state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assoc_press", DbType="VarChar(255)")]
		public string assoc_press
		{
			get
			{
				return this._assoc_press;
			}
			set
			{
				if ((this._assoc_press != value))
				{
					this._assoc_press = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_standard_federal_region", DbType="VarChar(255)")]
		public string standard_federal_region
		{
			get
			{
				return this._standard_federal_region;
			}
			set
			{
				if ((this._standard_federal_region != value))
				{
					this._standard_federal_region = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_census_region", DbType="VarChar(255)")]
		public string census_region
		{
			get
			{
				return this._census_region;
			}
			set
			{
				if ((this._census_region != value))
				{
					this._census_region = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_census_region_name", DbType="VarChar(255)")]
		public string census_region_name
		{
			get
			{
				return this._census_region_name;
			}
			set
			{
				if ((this._census_region_name != value))
				{
					this._census_region_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_census_division", DbType="VarChar(255)")]
		public string census_division
		{
			get
			{
				return this._census_division;
			}
			set
			{
				if ((this._census_division != value))
				{
					this._census_division = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_census_division_name", DbType="VarChar(255)")]
		public string census_division_name
		{
			get
			{
				return this._census_division_name;
			}
			set
			{
				if ((this._census_division_name != value))
				{
					this._census_division_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_circuit_court", DbType="VarChar(255)")]
		public string circuit_court
		{
			get
			{
				return this._circuit_court;
			}
			set
			{
				if ((this._circuit_court != value))
				{
					this._circuit_court = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="VENDOR.LKP_VENDOR_LOCKED")]
	public partial class LKP_VENDOR_LOCKED : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _VENDOR_NORM_NAME;
		
		private string _XREF_PARENT_VENDOR;
		
		private string _CONTACT_NAME;
		
		private string _CONTACT_OFFICE_PHONE;
		
		private string _CONTACT_MOBLE_PHONE;
		
		private string _CONTACT_EMAIL;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVENDOR_NORM_NAMEChanging(string value);
    partial void OnVENDOR_NORM_NAMEChanged();
    partial void OnXREF_PARENT_VENDORChanging(string value);
    partial void OnXREF_PARENT_VENDORChanged();
    partial void OnCONTACT_NAMEChanging(string value);
    partial void OnCONTACT_NAMEChanged();
    partial void OnCONTACT_OFFICE_PHONEChanging(string value);
    partial void OnCONTACT_OFFICE_PHONEChanged();
    partial void OnCONTACT_MOBLE_PHONEChanging(string value);
    partial void OnCONTACT_MOBLE_PHONEChanged();
    partial void OnCONTACT_EMAILChanging(string value);
    partial void OnCONTACT_EMAILChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public LKP_VENDOR_LOCKED()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VENDOR_NORM_NAME", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string VENDOR_NORM_NAME
		{
			get
			{
				return this._VENDOR_NORM_NAME;
			}
			set
			{
				if ((this._VENDOR_NORM_NAME != value))
				{
					this.OnVENDOR_NORM_NAMEChanging(value);
					this.SendPropertyChanging();
					this._VENDOR_NORM_NAME = value;
					this.SendPropertyChanged("VENDOR_NORM_NAME");
					this.OnVENDOR_NORM_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XREF_PARENT_VENDOR", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string XREF_PARENT_VENDOR
		{
			get
			{
				return this._XREF_PARENT_VENDOR;
			}
			set
			{
				if ((this._XREF_PARENT_VENDOR != value))
				{
					this.OnXREF_PARENT_VENDORChanging(value);
					this.SendPropertyChanging();
					this._XREF_PARENT_VENDOR = value;
					this.SendPropertyChanged("XREF_PARENT_VENDOR");
					this.OnXREF_PARENT_VENDORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACT_NAME", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string CONTACT_NAME
		{
			get
			{
				return this._CONTACT_NAME;
			}
			set
			{
				if ((this._CONTACT_NAME != value))
				{
					this.OnCONTACT_NAMEChanging(value);
					this.SendPropertyChanging();
					this._CONTACT_NAME = value;
					this.SendPropertyChanged("CONTACT_NAME");
					this.OnCONTACT_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACT_OFFICE_PHONE", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string CONTACT_OFFICE_PHONE
		{
			get
			{
				return this._CONTACT_OFFICE_PHONE;
			}
			set
			{
				if ((this._CONTACT_OFFICE_PHONE != value))
				{
					this.OnCONTACT_OFFICE_PHONEChanging(value);
					this.SendPropertyChanging();
					this._CONTACT_OFFICE_PHONE = value;
					this.SendPropertyChanged("CONTACT_OFFICE_PHONE");
					this.OnCONTACT_OFFICE_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACT_MOBLE_PHONE", DbType="NVarChar(20)")]
		public string CONTACT_MOBLE_PHONE
		{
			get
			{
				return this._CONTACT_MOBLE_PHONE;
			}
			set
			{
				if ((this._CONTACT_MOBLE_PHONE != value))
				{
					this.OnCONTACT_MOBLE_PHONEChanging(value);
					this.SendPropertyChanging();
					this._CONTACT_MOBLE_PHONE = value;
					this.SendPropertyChanged("CONTACT_MOBLE_PHONE");
					this.OnCONTACT_MOBLE_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACT_EMAIL", DbType="NVarChar(255)")]
		public string CONTACT_EMAIL
		{
			get
			{
				return this._CONTACT_EMAIL;
			}
			set
			{
				if ((this._CONTACT_EMAIL != value))
				{
					this.OnCONTACT_EMAILChanging(value);
					this.SendPropertyChanging();
					this._CONTACT_EMAIL = value;
					this.SendPropertyChanged("CONTACT_EMAIL");
					this.OnCONTACT_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
