#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMET.Server.Domain
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GAM_Complex_Op")]
	public partial class UserDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertApplicationLog(ApplicationLog instance);
    partial void UpdateApplicationLog(ApplicationLog instance);
    partial void DeleteApplicationLog(ApplicationLog instance);
    partial void InsertApplicationErrors2(ApplicationErrors2 instance);
    partial void UpdateApplicationErrors2(ApplicationErrors2 instance);
    partial void DeleteApplicationErrors2(ApplicationErrors2 instance);
    partial void InsertApplication_Role(Application_Role instance);
    partial void UpdateApplication_Role(Application_Role instance);
    partial void DeleteApplication_Role(Application_Role instance);
    partial void InsertAPP_AUTH_DESCRIPTION(APP_AUTH_DESCRIPTION instance);
    partial void UpdateAPP_AUTH_DESCRIPTION(APP_AUTH_DESCRIPTION instance);
    partial void DeleteAPP_AUTH_DESCRIPTION(APP_AUTH_DESCRIPTION instance);
    partial void InsertXXHR(XXHR instance);
    partial void UpdateXXHR(XXHR instance);
    partial void DeleteXXHR(XXHR instance);
    #endregion
		
		public UserDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UserDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UserDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UserDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ApplicationLog> ApplicationLogs
		{
			get
			{
				return this.GetTable<ApplicationLog>();
			}
		}
		
		public System.Data.Linq.Table<ApplicationErrors2> ApplicationErrors2s
		{
			get
			{
				return this.GetTable<ApplicationErrors2>();
			}
		}
		
		public System.Data.Linq.Table<Application_Role> Application_Roles
		{
			get
			{
				return this.GetTable<Application_Role>();
			}
		}
		
		public System.Data.Linq.Table<APP_AUTH_DESCRIPTION> APP_AUTH_DESCRIPTIONs
		{
			get
			{
				return this.GetTable<APP_AUTH_DESCRIPTION>();
			}
		}
		
		public System.Data.Linq.Table<XXHR> XXHRs
		{
			get
			{
				return this.GetTable<XXHR>();
			}
		}
		
		public System.Data.Linq.Table<APP_USAGE_W_GROUP> APP_USAGE_W_GROUPs
		{
			get
			{
				return this.GetTable<APP_USAGE_W_GROUP>();
			}
		}
		
		public System.Data.Linq.Table<APP_LOG_W_GROUP> APP_LOG_W_GROUPs
		{
			get
			{
				return this.GetTable<APP_LOG_W_GROUP>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="COMET.XXHR_HEIRARCHY", IsComposable=true)]
		public IQueryable<XXHR_HEIRARCHYResult> XXHR_HEIRARCHY([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User", DbType="NVarChar(150)")] string user)
		{
			return this.CreateMethodCallQuery<XXHR_HEIRARCHYResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="COMET.ApplicationLog")]
	public partial class ApplicationLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LogID;
		
		private string _Application_Name;
		
		private int _EmployeeID;
		
		private System.DateTime _LogTime;
		
		private string _ActionTaken;
		
		private EntityRef<XXHR> _XXHR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLogIDChanging(int value);
    partial void OnLogIDChanged();
    partial void OnApplication_NameChanging(string value);
    partial void OnApplication_NameChanged();
    partial void OnEmployeeIDChanging(int value);
    partial void OnEmployeeIDChanged();
    partial void OnLogTimeChanging(System.DateTime value);
    partial void OnLogTimeChanged();
    partial void OnActionTakenChanging(string value);
    partial void OnActionTakenChanged();
    #endregion
		
		public ApplicationLog()
		{
			this._XXHR = default(EntityRef<XXHR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LogID
		{
			get
			{
				return this._LogID;
			}
			set
			{
				if ((this._LogID != value))
				{
					this.OnLogIDChanging(value);
					this.SendPropertyChanging();
					this._LogID = value;
					this.SendPropertyChanged("LogID");
					this.OnLogIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Application_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Application_Name
		{
			get
			{
				return this._Application_Name;
			}
			set
			{
				if ((this._Application_Name != value))
				{
					this.OnApplication_NameChanging(value);
					this.SendPropertyChanging();
					this._Application_Name = value;
					this.SendPropertyChanged("Application_Name");
					this.OnApplication_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="Int NOT NULL")]
		public int EmployeeID
		{
			get
			{
				return this._EmployeeID;
			}
			set
			{
				if ((this._EmployeeID != value))
				{
					if (this._XXHR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmployeeIDChanging(value);
					this.SendPropertyChanging();
					this._EmployeeID = value;
					this.SendPropertyChanged("EmployeeID");
					this.OnEmployeeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogTime", DbType="DateTime NOT NULL")]
		public System.DateTime LogTime
		{
			get
			{
				return this._LogTime;
			}
			set
			{
				if ((this._LogTime != value))
				{
					this.OnLogTimeChanging(value);
					this.SendPropertyChanging();
					this._LogTime = value;
					this.SendPropertyChanged("LogTime");
					this.OnLogTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionTaken", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ActionTaken
		{
			get
			{
				return this._ActionTaken;
			}
			set
			{
				if ((this._ActionTaken != value))
				{
					this.OnActionTakenChanging(value);
					this.SendPropertyChanging();
					this._ActionTaken = value;
					this.SendPropertyChanged("ActionTaken");
					this.OnActionTakenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XXHR_ApplicationLog", Storage="_XXHR", ThisKey="EmployeeID", OtherKey="EMPLOYEE_ID", IsForeignKey=true)]
		public XXHR XXHR
		{
			get
			{
				return this._XXHR.Entity;
			}
			set
			{
				XXHR previousValue = this._XXHR.Entity;
				if (((previousValue != value) 
							|| (this._XXHR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._XXHR.Entity = null;
						previousValue.ApplicationLogs.Remove(this);
					}
					this._XXHR.Entity = value;
					if ((value != null))
					{
						value.ApplicationLogs.Add(this);
						this._EmployeeID = value.EMPLOYEE_ID;
					}
					else
					{
						this._EmployeeID = default(int);
					}
					this.SendPropertyChanged("XXHR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="COMET.ApplicationErrors2")]
	public partial class ApplicationErrors2 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ApplicationName;
		
		private string _PageName;
		
		private string _StepName;
		
		private int _EmployeeID;
		
		private System.DateTime _ErrorTime;
		
		private string _ErrorCode;
		
		private string _ErrorDetails;
		
		private EntityRef<XXHR> _XXHR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnApplicationNameChanging(string value);
    partial void OnApplicationNameChanged();
    partial void OnPageNameChanging(string value);
    partial void OnPageNameChanged();
    partial void OnStepNameChanging(string value);
    partial void OnStepNameChanged();
    partial void OnEmployeeIDChanging(int value);
    partial void OnEmployeeIDChanged();
    partial void OnErrorTimeChanging(System.DateTime value);
    partial void OnErrorTimeChanged();
    partial void OnErrorCodeChanging(string value);
    partial void OnErrorCodeChanged();
    partial void OnErrorDetailsChanging(string value);
    partial void OnErrorDetailsChanged();
    #endregion
		
		public ApplicationErrors2()
		{
			this._XXHR = default(EntityRef<XXHR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ApplicationName
		{
			get
			{
				return this._ApplicationName;
			}
			set
			{
				if ((this._ApplicationName != value))
				{
					this.OnApplicationNameChanging(value);
					this.SendPropertyChanging();
					this._ApplicationName = value;
					this.SendPropertyChanged("ApplicationName");
					this.OnApplicationNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PageName
		{
			get
			{
				return this._PageName;
			}
			set
			{
				if ((this._PageName != value))
				{
					this.OnPageNameChanging(value);
					this.SendPropertyChanging();
					this._PageName = value;
					this.SendPropertyChanged("PageName");
					this.OnPageNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StepName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string StepName
		{
			get
			{
				return this._StepName;
			}
			set
			{
				if ((this._StepName != value))
				{
					this.OnStepNameChanging(value);
					this.SendPropertyChanging();
					this._StepName = value;
					this.SendPropertyChanged("StepName");
					this.OnStepNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int EmployeeID
		{
			get
			{
				return this._EmployeeID;
			}
			set
			{
				if ((this._EmployeeID != value))
				{
					if (this._XXHR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmployeeIDChanging(value);
					this.SendPropertyChanging();
					this._EmployeeID = value;
					this.SendPropertyChanged("EmployeeID");
					this.OnEmployeeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorTime", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime ErrorTime
		{
			get
			{
				return this._ErrorTime;
			}
			set
			{
				if ((this._ErrorTime != value))
				{
					this.OnErrorTimeChanging(value);
					this.SendPropertyChanging();
					this._ErrorTime = value;
					this.SendPropertyChanged("ErrorTime");
					this.OnErrorTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorCode", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ErrorCode
		{
			get
			{
				return this._ErrorCode;
			}
			set
			{
				if ((this._ErrorCode != value))
				{
					this.OnErrorCodeChanging(value);
					this.SendPropertyChanging();
					this._ErrorCode = value;
					this.SendPropertyChanged("ErrorCode");
					this.OnErrorCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorDetails", DbType="VarChar(MAX)")]
		public string ErrorDetails
		{
			get
			{
				return this._ErrorDetails;
			}
			set
			{
				if ((this._ErrorDetails != value))
				{
					this.OnErrorDetailsChanging(value);
					this.SendPropertyChanging();
					this._ErrorDetails = value;
					this.SendPropertyChanged("ErrorDetails");
					this.OnErrorDetailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XXHR_ApplicationErrors2", Storage="_XXHR", ThisKey="EmployeeID", OtherKey="EMPLOYEE_ID", IsForeignKey=true)]
		public XXHR XXHR
		{
			get
			{
				return this._XXHR.Entity;
			}
			set
			{
				XXHR previousValue = this._XXHR.Entity;
				if (((previousValue != value) 
							|| (this._XXHR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._XXHR.Entity = null;
						previousValue.ApplicationErrors2s.Remove(this);
					}
					this._XXHR.Entity = value;
					if ((value != null))
					{
						value.ApplicationErrors2s.Add(this);
						this._EmployeeID = value.EMPLOYEE_ID;
					}
					else
					{
						this._EmployeeID = default(int);
					}
					this.SendPropertyChanged("XXHR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="COMET.Application_Roles")]
	public partial class Application_Role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EmployeeID;
		
		private int _AuthLevel;
		
		private bool _AckVersion;
		
		private EntityRef<APP_AUTH_DESCRIPTION> _APP_AUTH_DESCRIPTION;
		
		private EntityRef<XXHR> _XXHR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmployeeIDChanging(int value);
    partial void OnEmployeeIDChanged();
    partial void OnAuthLevelChanging(int value);
    partial void OnAuthLevelChanged();
    partial void OnAckVersionChanging(bool value);
    partial void OnAckVersionChanged();
    #endregion
		
		public Application_Role()
		{
			this._APP_AUTH_DESCRIPTION = default(EntityRef<APP_AUTH_DESCRIPTION>);
			this._XXHR = default(EntityRef<XXHR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int EmployeeID
		{
			get
			{
				return this._EmployeeID;
			}
			set
			{
				if ((this._EmployeeID != value))
				{
					if (this._XXHR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmployeeIDChanging(value);
					this.SendPropertyChanging();
					this._EmployeeID = value;
					this.SendPropertyChanged("EmployeeID");
					this.OnEmployeeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthLevel", DbType="Int NOT NULL")]
		public int AuthLevel
		{
			get
			{
				return this._AuthLevel;
			}
			set
			{
				if ((this._AuthLevel != value))
				{
					if (this._APP_AUTH_DESCRIPTION.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAuthLevelChanging(value);
					this.SendPropertyChanging();
					this._AuthLevel = value;
					this.SendPropertyChanged("AuthLevel");
					this.OnAuthLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AckVersion", DbType="Bit NOT NULL")]
		public bool AckVersion
		{
			get
			{
				return this._AckVersion;
			}
			set
			{
				if ((this._AckVersion != value))
				{
					this.OnAckVersionChanging(value);
					this.SendPropertyChanging();
					this._AckVersion = value;
					this.SendPropertyChanged("AckVersion");
					this.OnAckVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="APP_AUTH_DESCRIPTION_Application_Role", Storage="_APP_AUTH_DESCRIPTION", ThisKey="AuthLevel", OtherKey="Auth_Level", IsForeignKey=true)]
		public APP_AUTH_DESCRIPTION APP_AUTH_DESCRIPTION
		{
			get
			{
				return this._APP_AUTH_DESCRIPTION.Entity;
			}
			set
			{
				APP_AUTH_DESCRIPTION previousValue = this._APP_AUTH_DESCRIPTION.Entity;
				if (((previousValue != value) 
							|| (this._APP_AUTH_DESCRIPTION.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._APP_AUTH_DESCRIPTION.Entity = null;
						previousValue.Application_Roles.Remove(this);
					}
					this._APP_AUTH_DESCRIPTION.Entity = value;
					if ((value != null))
					{
						value.Application_Roles.Add(this);
						this._AuthLevel = value.Auth_Level;
					}
					else
					{
						this._AuthLevel = default(int);
					}
					this.SendPropertyChanged("APP_AUTH_DESCRIPTION");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XXHR_Application_Role", Storage="_XXHR", ThisKey="EmployeeID", OtherKey="EMPLOYEE_ID", IsForeignKey=true)]
		public XXHR XXHR
		{
			get
			{
				return this._XXHR.Entity;
			}
			set
			{
				XXHR previousValue = this._XXHR.Entity;
				if (((previousValue != value) 
							|| (this._XXHR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._XXHR.Entity = null;
						previousValue.Application_Role = null;
					}
					this._XXHR.Entity = value;
					if ((value != null))
					{
						value.Application_Role = this;
						this._EmployeeID = value.EMPLOYEE_ID;
					}
					else
					{
						this._EmployeeID = default(int);
					}
					this.SendPropertyChanged("XXHR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="COMET.APP_AUTH_DESCRIPTION")]
	public partial class APP_AUTH_DESCRIPTION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Auth_Level;
		
		private string _Auth_Description;
		
		private EntitySet<Application_Role> _Application_Roles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAuth_LevelChanging(int value);
    partial void OnAuth_LevelChanged();
    partial void OnAuth_DescriptionChanging(string value);
    partial void OnAuth_DescriptionChanged();
    #endregion
		
		public APP_AUTH_DESCRIPTION()
		{
			this._Application_Roles = new EntitySet<Application_Role>(new Action<Application_Role>(this.attach_Application_Roles), new Action<Application_Role>(this.detach_Application_Roles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Auth_Level", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Auth_Level
		{
			get
			{
				return this._Auth_Level;
			}
			set
			{
				if ((this._Auth_Level != value))
				{
					this.OnAuth_LevelChanging(value);
					this.SendPropertyChanging();
					this._Auth_Level = value;
					this.SendPropertyChanged("Auth_Level");
					this.OnAuth_LevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Auth_Description", DbType="NVarChar(100)")]
		public string Auth_Description
		{
			get
			{
				return this._Auth_Description;
			}
			set
			{
				if ((this._Auth_Description != value))
				{
					this.OnAuth_DescriptionChanging(value);
					this.SendPropertyChanging();
					this._Auth_Description = value;
					this.SendPropertyChanged("Auth_Description");
					this.OnAuth_DescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="APP_AUTH_DESCRIPTION_Application_Role", Storage="_Application_Roles", ThisKey="Auth_Level", OtherKey="AuthLevel")]
		public EntitySet<Application_Role> Application_Roles
		{
			get
			{
				return this._Application_Roles;
			}
			set
			{
				this._Application_Roles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Application_Roles(Application_Role entity)
		{
			this.SendPropertyChanging();
			entity.APP_AUTH_DESCRIPTION = this;
		}
		
		private void detach_Application_Roles(Application_Role entity)
		{
			this.SendPropertyChanging();
			entity.APP_AUTH_DESCRIPTION = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="COMET.XXHR")]
	public partial class XXHR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EMPLOYEE_ID;
		
		private string _NAME;
		
		private string _SYS_USER;
		
		private string _JOB_NAME;
		
		private string _MANAGER;
		
		private string _DEPARTMENT;
		
		private string _OFFICE_NAME;
		
		private string _STREET_ADDRESS;
		
		private string _CITY;
		
		private string _POSTALCODE;
		
		private string _STATE_CD;
		
		private string _HOME_DIRECTORY;
		
		private string _EMAIL_ADDRESS;
		
		private string _MEMBER_OF;
		
		private System.Nullable<System.DateTime> _HIRE_DATE;
		
		private System.Nullable<System.DateTime> _TERM_DATE;
		
		private System.Nullable<System.DateTime> _LAST_UPDATED;
		
		private string _TELEPHONE;
		
		private string _MOBILE;
		
		private string _DISPLAY_NAME;
		
		private EntitySet<ApplicationLog> _ApplicationLogs;
		
		private EntitySet<ApplicationErrors2> _ApplicationErrors2s;
		
		private EntityRef<Application_Role> _Application_Role;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEMPLOYEE_IDChanging(int value);
    partial void OnEMPLOYEE_IDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnSYS_USERChanging(string value);
    partial void OnSYS_USERChanged();
    partial void OnJOB_NAMEChanging(string value);
    partial void OnJOB_NAMEChanged();
    partial void OnMANAGERChanging(string value);
    partial void OnMANAGERChanged();
    partial void OnDEPARTMENTChanging(string value);
    partial void OnDEPARTMENTChanged();
    partial void OnOFFICE_NAMEChanging(string value);
    partial void OnOFFICE_NAMEChanged();
    partial void OnSTREET_ADDRESSChanging(string value);
    partial void OnSTREET_ADDRESSChanged();
    partial void OnCITYChanging(string value);
    partial void OnCITYChanged();
    partial void OnPOSTALCODEChanging(string value);
    partial void OnPOSTALCODEChanged();
    partial void OnSTATE_CDChanging(string value);
    partial void OnSTATE_CDChanged();
    partial void OnHOME_DIRECTORYChanging(string value);
    partial void OnHOME_DIRECTORYChanged();
    partial void OnEMAIL_ADDRESSChanging(string value);
    partial void OnEMAIL_ADDRESSChanged();
    partial void OnMEMBER_OFChanging(string value);
    partial void OnMEMBER_OFChanged();
    partial void OnHIRE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnHIRE_DATEChanged();
    partial void OnTERM_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnTERM_DATEChanged();
    partial void OnLAST_UPDATEDChanging(System.Nullable<System.DateTime> value);
    partial void OnLAST_UPDATEDChanged();
    partial void OnTELEPHONEChanging(string value);
    partial void OnTELEPHONEChanged();
    partial void OnMOBILEChanging(string value);
    partial void OnMOBILEChanged();
    partial void OnDISPLAY_NAMEChanging(string value);
    partial void OnDISPLAY_NAMEChanged();
    #endregion
		
		public XXHR()
		{
			this._ApplicationLogs = new EntitySet<ApplicationLog>(new Action<ApplicationLog>(this.attach_ApplicationLogs), new Action<ApplicationLog>(this.detach_ApplicationLogs));
			this._ApplicationErrors2s = new EntitySet<ApplicationErrors2>(new Action<ApplicationErrors2>(this.attach_ApplicationErrors2s), new Action<ApplicationErrors2>(this.detach_ApplicationErrors2s));
			this._Application_Role = default(EntityRef<Application_Role>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int EMPLOYEE_ID
		{
			get
			{
				return this._EMPLOYEE_ID;
			}
			set
			{
				if ((this._EMPLOYEE_ID != value))
				{
					this.OnEMPLOYEE_IDChanging(value);
					this.SendPropertyChanging();
					this._EMPLOYEE_ID = value;
					this.SendPropertyChanged("EMPLOYEE_ID");
					this.OnEMPLOYEE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYS_USER", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string SYS_USER
		{
			get
			{
				return this._SYS_USER;
			}
			set
			{
				if ((this._SYS_USER != value))
				{
					this.OnSYS_USERChanging(value);
					this.SendPropertyChanging();
					this._SYS_USER = value;
					this.SendPropertyChanged("SYS_USER");
					this.OnSYS_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_NAME", DbType="VarChar(100)")]
		public string JOB_NAME
		{
			get
			{
				return this._JOB_NAME;
			}
			set
			{
				if ((this._JOB_NAME != value))
				{
					this.OnJOB_NAMEChanging(value);
					this.SendPropertyChanging();
					this._JOB_NAME = value;
					this.SendPropertyChanged("JOB_NAME");
					this.OnJOB_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAGER", DbType="VarChar(150)")]
		public string MANAGER
		{
			get
			{
				return this._MANAGER;
			}
			set
			{
				if ((this._MANAGER != value))
				{
					this.OnMANAGERChanging(value);
					this.SendPropertyChanging();
					this._MANAGER = value;
					this.SendPropertyChanged("MANAGER");
					this.OnMANAGERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTMENT", DbType="VarChar(100)")]
		public string DEPARTMENT
		{
			get
			{
				return this._DEPARTMENT;
			}
			set
			{
				if ((this._DEPARTMENT != value))
				{
					this.OnDEPARTMENTChanging(value);
					this.SendPropertyChanging();
					this._DEPARTMENT = value;
					this.SendPropertyChanged("DEPARTMENT");
					this.OnDEPARTMENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFFICE_NAME", DbType="VarChar(100)")]
		public string OFFICE_NAME
		{
			get
			{
				return this._OFFICE_NAME;
			}
			set
			{
				if ((this._OFFICE_NAME != value))
				{
					this.OnOFFICE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._OFFICE_NAME = value;
					this.SendPropertyChanged("OFFICE_NAME");
					this.OnOFFICE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STREET_ADDRESS", DbType="VarChar(150)")]
		public string STREET_ADDRESS
		{
			get
			{
				return this._STREET_ADDRESS;
			}
			set
			{
				if ((this._STREET_ADDRESS != value))
				{
					this.OnSTREET_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._STREET_ADDRESS = value;
					this.SendPropertyChanged("STREET_ADDRESS");
					this.OnSTREET_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="VarChar(50)")]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this.OnCITYChanging(value);
					this.SendPropertyChanging();
					this._CITY = value;
					this.SendPropertyChanged("CITY");
					this.OnCITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTALCODE", DbType="VarChar(10)")]
		public string POSTALCODE
		{
			get
			{
				return this._POSTALCODE;
			}
			set
			{
				if ((this._POSTALCODE != value))
				{
					this.OnPOSTALCODEChanging(value);
					this.SendPropertyChanging();
					this._POSTALCODE = value;
					this.SendPropertyChanged("POSTALCODE");
					this.OnPOSTALCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_CD", DbType="VarChar(50)")]
		public string STATE_CD
		{
			get
			{
				return this._STATE_CD;
			}
			set
			{
				if ((this._STATE_CD != value))
				{
					this.OnSTATE_CDChanging(value);
					this.SendPropertyChanging();
					this._STATE_CD = value;
					this.SendPropertyChanged("STATE_CD");
					this.OnSTATE_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOME_DIRECTORY", DbType="VarChar(200)")]
		public string HOME_DIRECTORY
		{
			get
			{
				return this._HOME_DIRECTORY;
			}
			set
			{
				if ((this._HOME_DIRECTORY != value))
				{
					this.OnHOME_DIRECTORYChanging(value);
					this.SendPropertyChanging();
					this._HOME_DIRECTORY = value;
					this.SendPropertyChanged("HOME_DIRECTORY");
					this.OnHOME_DIRECTORYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL_ADDRESS", DbType="VarChar(100)")]
		public string EMAIL_ADDRESS
		{
			get
			{
				return this._EMAIL_ADDRESS;
			}
			set
			{
				if ((this._EMAIL_ADDRESS != value))
				{
					this.OnEMAIL_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._EMAIL_ADDRESS = value;
					this.SendPropertyChanged("EMAIL_ADDRESS");
					this.OnEMAIL_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEMBER_OF", DbType="VarChar(MAX)")]
		public string MEMBER_OF
		{
			get
			{
				return this._MEMBER_OF;
			}
			set
			{
				if ((this._MEMBER_OF != value))
				{
					this.OnMEMBER_OFChanging(value);
					this.SendPropertyChanging();
					this._MEMBER_OF = value;
					this.SendPropertyChanged("MEMBER_OF");
					this.OnMEMBER_OFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIRE_DATE", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> HIRE_DATE
		{
			get
			{
				return this._HIRE_DATE;
			}
			set
			{
				if ((this._HIRE_DATE != value))
				{
					this.OnHIRE_DATEChanging(value);
					this.SendPropertyChanging();
					this._HIRE_DATE = value;
					this.SendPropertyChanged("HIRE_DATE");
					this.OnHIRE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERM_DATE", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> TERM_DATE
		{
			get
			{
				return this._TERM_DATE;
			}
			set
			{
				if ((this._TERM_DATE != value))
				{
					this.OnTERM_DATEChanging(value);
					this.SendPropertyChanging();
					this._TERM_DATE = value;
					this.SendPropertyChanged("TERM_DATE");
					this.OnTERM_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATED", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> LAST_UPDATED
		{
			get
			{
				return this._LAST_UPDATED;
			}
			set
			{
				if ((this._LAST_UPDATED != value))
				{
					this.OnLAST_UPDATEDChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATED = value;
					this.SendPropertyChanged("LAST_UPDATED");
					this.OnLAST_UPDATEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEPHONE", DbType="VarChar(50)")]
		public string TELEPHONE
		{
			get
			{
				return this._TELEPHONE;
			}
			set
			{
				if ((this._TELEPHONE != value))
				{
					this.OnTELEPHONEChanging(value);
					this.SendPropertyChanging();
					this._TELEPHONE = value;
					this.SendPropertyChanged("TELEPHONE");
					this.OnTELEPHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOBILE", DbType="VarChar(50)")]
		public string MOBILE
		{
			get
			{
				return this._MOBILE;
			}
			set
			{
				if ((this._MOBILE != value))
				{
					this.OnMOBILEChanging(value);
					this.SendPropertyChanging();
					this._MOBILE = value;
					this.SendPropertyChanged("MOBILE");
					this.OnMOBILEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISPLAY_NAME", DbType="VarChar(500)")]
		public string DISPLAY_NAME
		{
			get
			{
				return this._DISPLAY_NAME;
			}
			set
			{
				if ((this._DISPLAY_NAME != value))
				{
					this.OnDISPLAY_NAMEChanging(value);
					this.SendPropertyChanging();
					this._DISPLAY_NAME = value;
					this.SendPropertyChanged("DISPLAY_NAME");
					this.OnDISPLAY_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XXHR_ApplicationLog", Storage="_ApplicationLogs", ThisKey="EMPLOYEE_ID", OtherKey="EmployeeID")]
		public EntitySet<ApplicationLog> ApplicationLogs
		{
			get
			{
				return this._ApplicationLogs;
			}
			set
			{
				this._ApplicationLogs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XXHR_ApplicationErrors2", Storage="_ApplicationErrors2s", ThisKey="EMPLOYEE_ID", OtherKey="EmployeeID")]
		public EntitySet<ApplicationErrors2> ApplicationErrors2s
		{
			get
			{
				return this._ApplicationErrors2s;
			}
			set
			{
				this._ApplicationErrors2s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XXHR_Application_Role", Storage="_Application_Role", ThisKey="EMPLOYEE_ID", OtherKey="EmployeeID", IsUnique=true, IsForeignKey=false)]
		public Application_Role Application_Role
		{
			get
			{
				return this._Application_Role.Entity;
			}
			set
			{
				Application_Role previousValue = this._Application_Role.Entity;
				if (((previousValue != value) 
							|| (this._Application_Role.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Application_Role.Entity = null;
						previousValue.XXHR = null;
					}
					this._Application_Role.Entity = value;
					if ((value != null))
					{
						value.XXHR = this;
					}
					this.SendPropertyChanged("Application_Role");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ApplicationLogs(ApplicationLog entity)
		{
			this.SendPropertyChanging();
			entity.XXHR = this;
		}
		
		private void detach_ApplicationLogs(ApplicationLog entity)
		{
			this.SendPropertyChanging();
			entity.XXHR = null;
		}
		
		private void attach_ApplicationErrors2s(ApplicationErrors2 entity)
		{
			this.SendPropertyChanging();
			entity.XXHR = this;
		}
		
		private void detach_ApplicationErrors2s(ApplicationErrors2 entity)
		{
			this.SendPropertyChanging();
			entity.XXHR = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="COMET.APP_USAGE_W_GROUP")]
	public partial class APP_USAGE_W_GROUP
	{
		
		private string _GROUPING;
		
		private System.Nullable<System.DateTime> _WeekStart;
		
		private System.Nullable<int> _Logs;
		
		public APP_USAGE_W_GROUP()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUPING", DbType="VarChar(100)")]
		public string GROUPING
		{
			get
			{
				return this._GROUPING;
			}
			set
			{
				if ((this._GROUPING != value))
				{
					this._GROUPING = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeekStart", DbType="DateTime")]
		public System.Nullable<System.DateTime> WeekStart
		{
			get
			{
				return this._WeekStart;
			}
			set
			{
				if ((this._WeekStart != value))
				{
					this._WeekStart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logs", DbType="Int")]
		public System.Nullable<int> Logs
		{
			get
			{
				return this._Logs;
			}
			set
			{
				if ((this._Logs != value))
				{
					this._Logs = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="COMET.APP_LOG_W_GROUP")]
	public partial class APP_LOG_W_GROUP
	{
		
		private int _LogID;
		
		private string _Application_Name;
		
		private string _SysUser;
		
		private int _EmployeeID;
		
		private System.DateTime _LogTime;
		
		private string _ActionTaken;
		
		private string _GROUPING;
		
		public APP_LOG_W_GROUP()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogID", DbType="Int NOT NULL")]
		public int LogID
		{
			get
			{
				return this._LogID;
			}
			set
			{
				if ((this._LogID != value))
				{
					this._LogID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Application_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Application_Name
		{
			get
			{
				return this._Application_Name;
			}
			set
			{
				if ((this._Application_Name != value))
				{
					this._Application_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SysUser", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string SysUser
		{
			get
			{
				return this._SysUser;
			}
			set
			{
				if ((this._SysUser != value))
				{
					this._SysUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="Int NOT NULL")]
		public int EmployeeID
		{
			get
			{
				return this._EmployeeID;
			}
			set
			{
				if ((this._EmployeeID != value))
				{
					this._EmployeeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogTime", DbType="DateTime NOT NULL")]
		public System.DateTime LogTime
		{
			get
			{
				return this._LogTime;
			}
			set
			{
				if ((this._LogTime != value))
				{
					this._LogTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionTaken", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ActionTaken
		{
			get
			{
				return this._ActionTaken;
			}
			set
			{
				if ((this._ActionTaken != value))
				{
					this._ActionTaken = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUPING", DbType="VarChar(100)")]
		public string GROUPING
		{
			get
			{
				return this._GROUPING;
			}
			set
			{
				if ((this._GROUPING != value))
				{
					this._GROUPING = value;
				}
			}
		}
	}
	
	public partial class XXHR_HEIRARCHYResult
	{
		
		private int _EMPLOYEE_ID;
		
		private string _NAME;
		
		private string _SYS_USER;
		
		private string _JOB_NAME;
		
		private System.Nullable<int> _MANAGER1_ID;
		
		private string _MANAGER1_NT;
		
		private string _MANAGER1;
		
		private string _MANAGER1_JOB_NAME;
		
		private string _MANAGER1_EMAIL;
		
		private System.Nullable<int> _MANAGER2_ID;
		
		private string _MANAGER2_NT;
		
		private string _MANAGER2;
		
		private string _MANAGER2_JOB_NAME;
		
		private string _MANAGER2_EMAIL;
		
		private System.Nullable<int> _MANAGER3_ID;
		
		private string _MANAGER3_NT;
		
		private string _MANAGER3;
		
		private string _MANAGER3_JOB_NAME;
		
		private string _MANAGER3_EMAIL;
		
		private System.Nullable<int> _MANAGER4_ID;
		
		private string _MANAGER4_NT;
		
		private string _MANAGER4;
		
		private string _MANAGER4_JOB_NAME;
		
		private string _MANAGER4_EMAIL;
		
		private string _DEPARTMENT;
		
		private string _OFFICE_NAME;
		
		private string _STREET_ADDRESS;
		
		private string _CITY;
		
		private string _POSTALCODE;
		
		private string _STATE_CD;
		
		private string _HOME_DIRECTORY;
		
		private string _EMAIL_ADDRESS;
		
		private string _MEMBER_OF;
		
		private System.Nullable<System.DateTime> _HIRE_DATE;
		
		private System.Nullable<System.DateTime> _TERM_DATE;
		
		private string _TELEPHONE;
		
		private string _MOBILE;
		
		public XXHR_HEIRARCHYResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_ID", DbType="Int NOT NULL")]
		public int EMPLOYEE_ID
		{
			get
			{
				return this._EMPLOYEE_ID;
			}
			set
			{
				if ((this._EMPLOYEE_ID != value))
				{
					this._EMPLOYEE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYS_USER", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string SYS_USER
		{
			get
			{
				return this._SYS_USER;
			}
			set
			{
				if ((this._SYS_USER != value))
				{
					this._SYS_USER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_NAME", DbType="VarChar(100)")]
		public string JOB_NAME
		{
			get
			{
				return this._JOB_NAME;
			}
			set
			{
				if ((this._JOB_NAME != value))
				{
					this._JOB_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAGER1_ID", DbType="Int")]
		public System.Nullable<int> MANAGER1_ID
		{
			get
			{
				return this._MANAGER1_ID;
			}
			set
			{
				if ((this._MANAGER1_ID != value))
				{
					this._MANAGER1_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAGER1_NT", DbType="NVarChar(100)")]
		public string MANAGER1_NT
		{
			get
			{
				return this._MANAGER1_NT;
			}
			set
			{
				if ((this._MANAGER1_NT != value))
				{
					this._MANAGER1_NT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAGER1", DbType="VarChar(100)")]
		public string MANAGER1
		{
			get
			{
				return this._MANAGER1;
			}
			set
			{
				if ((this._MANAGER1 != value))
				{
					this._MANAGER1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAGER1_JOB_NAME", DbType="VarChar(100)")]
		public string MANAGER1_JOB_NAME
		{
			get
			{
				return this._MANAGER1_JOB_NAME;
			}
			set
			{
				if ((this._MANAGER1_JOB_NAME != value))
				{
					this._MANAGER1_JOB_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAGER1_EMAIL", DbType="VarChar(100)")]
		public string MANAGER1_EMAIL
		{
			get
			{
				return this._MANAGER1_EMAIL;
			}
			set
			{
				if ((this._MANAGER1_EMAIL != value))
				{
					this._MANAGER1_EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAGER2_ID", DbType="Int")]
		public System.Nullable<int> MANAGER2_ID
		{
			get
			{
				return this._MANAGER2_ID;
			}
			set
			{
				if ((this._MANAGER2_ID != value))
				{
					this._MANAGER2_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAGER2_NT", DbType="NVarChar(100)")]
		public string MANAGER2_NT
		{
			get
			{
				return this._MANAGER2_NT;
			}
			set
			{
				if ((this._MANAGER2_NT != value))
				{
					this._MANAGER2_NT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAGER2", DbType="VarChar(100)")]
		public string MANAGER2
		{
			get
			{
				return this._MANAGER2;
			}
			set
			{
				if ((this._MANAGER2 != value))
				{
					this._MANAGER2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAGER2_JOB_NAME", DbType="VarChar(100)")]
		public string MANAGER2_JOB_NAME
		{
			get
			{
				return this._MANAGER2_JOB_NAME;
			}
			set
			{
				if ((this._MANAGER2_JOB_NAME != value))
				{
					this._MANAGER2_JOB_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAGER2_EMAIL", DbType="VarChar(100)")]
		public string MANAGER2_EMAIL
		{
			get
			{
				return this._MANAGER2_EMAIL;
			}
			set
			{
				if ((this._MANAGER2_EMAIL != value))
				{
					this._MANAGER2_EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAGER3_ID", DbType="Int")]
		public System.Nullable<int> MANAGER3_ID
		{
			get
			{
				return this._MANAGER3_ID;
			}
			set
			{
				if ((this._MANAGER3_ID != value))
				{
					this._MANAGER3_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAGER3_NT", DbType="NVarChar(100)")]
		public string MANAGER3_NT
		{
			get
			{
				return this._MANAGER3_NT;
			}
			set
			{
				if ((this._MANAGER3_NT != value))
				{
					this._MANAGER3_NT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAGER3", DbType="VarChar(100)")]
		public string MANAGER3
		{
			get
			{
				return this._MANAGER3;
			}
			set
			{
				if ((this._MANAGER3 != value))
				{
					this._MANAGER3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAGER3_JOB_NAME", DbType="VarChar(100)")]
		public string MANAGER3_JOB_NAME
		{
			get
			{
				return this._MANAGER3_JOB_NAME;
			}
			set
			{
				if ((this._MANAGER3_JOB_NAME != value))
				{
					this._MANAGER3_JOB_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAGER3_EMAIL", DbType="VarChar(100)")]
		public string MANAGER3_EMAIL
		{
			get
			{
				return this._MANAGER3_EMAIL;
			}
			set
			{
				if ((this._MANAGER3_EMAIL != value))
				{
					this._MANAGER3_EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAGER4_ID", DbType="Int")]
		public System.Nullable<int> MANAGER4_ID
		{
			get
			{
				return this._MANAGER4_ID;
			}
			set
			{
				if ((this._MANAGER4_ID != value))
				{
					this._MANAGER4_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAGER4_NT", DbType="NVarChar(100)")]
		public string MANAGER4_NT
		{
			get
			{
				return this._MANAGER4_NT;
			}
			set
			{
				if ((this._MANAGER4_NT != value))
				{
					this._MANAGER4_NT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAGER4", DbType="VarChar(100)")]
		public string MANAGER4
		{
			get
			{
				return this._MANAGER4;
			}
			set
			{
				if ((this._MANAGER4 != value))
				{
					this._MANAGER4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAGER4_JOB_NAME", DbType="VarChar(100)")]
		public string MANAGER4_JOB_NAME
		{
			get
			{
				return this._MANAGER4_JOB_NAME;
			}
			set
			{
				if ((this._MANAGER4_JOB_NAME != value))
				{
					this._MANAGER4_JOB_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAGER4_EMAIL", DbType="VarChar(100)")]
		public string MANAGER4_EMAIL
		{
			get
			{
				return this._MANAGER4_EMAIL;
			}
			set
			{
				if ((this._MANAGER4_EMAIL != value))
				{
					this._MANAGER4_EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTMENT", DbType="VarChar(100)")]
		public string DEPARTMENT
		{
			get
			{
				return this._DEPARTMENT;
			}
			set
			{
				if ((this._DEPARTMENT != value))
				{
					this._DEPARTMENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFFICE_NAME", DbType="VarChar(100)")]
		public string OFFICE_NAME
		{
			get
			{
				return this._OFFICE_NAME;
			}
			set
			{
				if ((this._OFFICE_NAME != value))
				{
					this._OFFICE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STREET_ADDRESS", DbType="VarChar(100)")]
		public string STREET_ADDRESS
		{
			get
			{
				return this._STREET_ADDRESS;
			}
			set
			{
				if ((this._STREET_ADDRESS != value))
				{
					this._STREET_ADDRESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="VarChar(50)")]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this._CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTALCODE", DbType="VarChar(8)")]
		public string POSTALCODE
		{
			get
			{
				return this._POSTALCODE;
			}
			set
			{
				if ((this._POSTALCODE != value))
				{
					this._POSTALCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_CD", DbType="VarChar(20)")]
		public string STATE_CD
		{
			get
			{
				return this._STATE_CD;
			}
			set
			{
				if ((this._STATE_CD != value))
				{
					this._STATE_CD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOME_DIRECTORY", DbType="VarChar(200)")]
		public string HOME_DIRECTORY
		{
			get
			{
				return this._HOME_DIRECTORY;
			}
			set
			{
				if ((this._HOME_DIRECTORY != value))
				{
					this._HOME_DIRECTORY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL_ADDRESS", DbType="VarChar(100)")]
		public string EMAIL_ADDRESS
		{
			get
			{
				return this._EMAIL_ADDRESS;
			}
			set
			{
				if ((this._EMAIL_ADDRESS != value))
				{
					this._EMAIL_ADDRESS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEMBER_OF", DbType="VarChar(MAX)")]
		public string MEMBER_OF
		{
			get
			{
				return this._MEMBER_OF;
			}
			set
			{
				if ((this._MEMBER_OF != value))
				{
					this._MEMBER_OF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIRE_DATE", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> HIRE_DATE
		{
			get
			{
				return this._HIRE_DATE;
			}
			set
			{
				if ((this._HIRE_DATE != value))
				{
					this._HIRE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERM_DATE", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> TERM_DATE
		{
			get
			{
				return this._TERM_DATE;
			}
			set
			{
				if ((this._TERM_DATE != value))
				{
					this._TERM_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEPHONE", DbType="VarChar(30)")]
		public string TELEPHONE
		{
			get
			{
				return this._TELEPHONE;
			}
			set
			{
				if ((this._TELEPHONE != value))
				{
					this._TELEPHONE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOBILE", DbType="VarChar(30)")]
		public string MOBILE
		{
			get
			{
				return this._MOBILE;
			}
			set
			{
				if ((this._MOBILE != value))
				{
					this._MOBILE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
